### ISSUE TITLE
Please include expo app setup in Introduction.GettingStarted.md

### ISSUE THREAD

**Issue by Martian2Lee** [wix/detox#698] opened 2018-04-29 07:50 UTC

**Comment by DanielMSchmidt** [comment] 2018-04-29 07:52
Hey, thank you for your issue. Could you please explain a bit more detailed what you would like to see? Is there a link missing or the explanation itself? Either way, it would be nice if you could provide a PR for that. If you have never done that before please tell me and I will guide you through the process 👍

**Comment by Martian2Lee** [comment] 2018-04-29 07:57
Hi @DanielMSchmidt, I used `create-react-native-app` for my project, if I want to use `detox`, how should I config my `package.json`?

**Comment by DanielMSchmidt** [comment] 2018-04-29 08:01
I think the instructions you are searching for are not yet on master. There is this PR #630 adding them to our docs. Please look there for the information you seek right now, I will ping the persons involved to get this to master.

I will close this issue as it's a duplicate of #236

**Closed by DanielMSchmidt** 2018-04-29 08:01 UTC
