### ISSUE TITLE
Can you not show the Hierarchy section when having an error?

### ISSUE THREAD

**Issue by yanivshor** [wix/Detox#1350] opened 2019-05-01 11:54 UTC
Hi, when I run tests and get an error the iTerm gets over populated by the Hierarchy section and I can't scroll up to see the top of the error. Is it possible to not show the Hierarchy section, or reduce it?

**Comment by AlexK777** [comment] 2019-05-01 18:38
This one looks like a duplicate of #992 and #1227 .

**Comment by Niryo** [comment] 2019-05-02 09:00
We should print the hierarchy only on --log-level verbose or trace, and keep the regular logs minimal.
I am using detox heavily and I rarely use those logs, we should definitely make them optional.

**Comment by LeoNatan** [comment] 2019-05-02 15:27
This has been discussed many times and will not be accepted sorry. This is a feature we hold on high regard.

**Closed by LeoNatan** 2019-05-02 15:27 UTC
Labels: type: triage/enhancement

**Comment by bintoll** [comment] 2019-05-05 14:09
I understand that it is closed and saw that it was discussed, however would also like to add a comment to show the developers that this feature is really wanted. I think people ask here just for some flag that will remove this log like ```--no-hierarchy``` or something like this. I think it is not a big deal to add this feature for developers and it will make the software more friendly and flexible. Thanks!

**Comment by Niryo** [comment] 2019-05-05 14:47
@bintoll, The problem occurs also with React Navigation, it's not really related.
