### ISSUE TITLE
error in  clearDeviceRegistryLockFile() when running detox test

### ISSUE THREAD

**Issue by dat00ste** [wix/detox#771] opened 2018-06-05 11:20 UTC
#### Description
Since detox 7.4.0 I cannot start detox test. It fails on clearDeviceRegistryLockFile that was added in #609.
I'm using windows.

$ detox test -c android.emu.release --loglevel verbose
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\stina\AppData\Local\data\Detox\device.registry.state.lock'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at clearDeviceRegistryLockFile (C:\Users\stina\code\App\powerup\node_modules\detox\local-cli\detox-test.js:171:6)

detox 7.3.7 works fine (with some minor manual changes )

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.4.0
* React Native: 0.55.3
* Node: 8.11.1
* Device: -
* Xcode: -
* macOS: -

**Comment by noomorph** [comment] 2018-06-05 17:13
If nobody takes this issue, I can try to reproduce after June 10th, after I return from vacation. Or maybe @simonbuchan might want to take a look?

**Comment by simonbuchan** [comment] 2018-06-05 19:07
Hmm, I migrated up to 7.4.0 without trouble. Looks like it just hasn't created the data directory, so if that got broken, shouldn't be too hard to track down (and maybe isn't even windows?)

**Comment by noomorph** [comment] 2018-06-06 03:14
> Hmm, I migrated up to 7.4.0 without trouble. 

That was actually the point I was trying to check on. Thanks much, Simon!

**Comment by dat00ste** [comment] 2018-06-07 06:58
Thanks for the replies!
 Yes, the data directory is missing, when should it be created?

**Comment by rotemmiz** [comment] 2018-06-07 07:08
This is an actual issue. We need to ensure the directory will be created if doesn't exist

**Comment by rotemmiz** [comment] 2018-06-10 10:55
Fixed in #781

**Closed by rotemmiz** 2018-06-10 10:55 UTC
Labels: type: accepted/bug
