### ISSUE TITLE
Change API to use Promises instead of callbacks

### ISSUE THREAD

**Issue by artald** [wix/detox#57] opened 2016-12-01 14:56 UTC
For example, I would like to be able to use async/await when calling `simulator.deleteAndRelaunchApp()`

**Comment by DanielZlotin** [comment] 2016-12-01 15:35
This is a must if we want to keep our sanity

**Comment by LeoNatan** [comment] 2017-01-10 20:12
Seems like a duplicate of #38 .

**Closed by LeoNatan** 2017-01-10 20:12 UTC
