### ISSUE TITLE
Detox 19.3.0 causes "View is not hittable at its visible point" failures

### ISSUE THREAD

**Issue by Vannevelj** [wix/Detox#3130] opened 2021-12-08 12:39 UTC
### Description
I'm on Detox 19.1.0. Upgrading to 19.2.0 works just fine and I've got a nice green run of my 120 tests. If I further bump to 19.3.0 then I get a large amount of failures (20+) all with the same error:

```
DetoxRuntimeError: Test Failed: View is not hittable at its visible point. Error: Failed to hit view at point {992, 197} with `hitTest`.
- Origin view: <UIView: 0x7fa90e910b90; frame = (0 0; 1024 1366); autoresize = W+H; layer = <CALayer: 0x600000d31320>>
- Absolute origin: {0, 0}
- Hitten: <UIView: 0x7fa90e910b90; frame = (0 0; 1024 1366); autoresize = W+H; layer = <CALayer: 0x600000d31320>>
- Target view: <RCTImageView: 0x7fa91cfccb30; reactTag: 923; frame = (290 16; 32 32); clipsToBounds = YES; layer = <CALayer: 0x600000d2f220>>
- Relative point: {992, 197}
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Upgrade to Detox 19.3.0

#### Environment

 - Detox: 19.3.0
 - React Native: 0.65.1
 - Node: 12.13.0
 - Device: iPad Mini 6th Generation (15.0) & iPad Pro 12.9-inch (5th Generation)
 - Xcode: 13.0
 - iOS: 11.0
 - macOS: 11.6 Big Sur
 - Test-runner (select one): `jest-circus`

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

https://gist.github.com/Vannevelj/ee918001bffc5ae4c794cd76f398cff8

**Comment by asafkorem** [comment] 2021-12-08 12:44
Hi @Vannevelj, we indeed changed the implementation of UI gestures in the latest version by adding an assertion for hittability.

Can you please provide here the test's code and the tested view's code?

**Comment by asafkorem** [comment] 2021-12-08 12:48
Also, are you able to execute the expected flow manually?

**Comment by Vannevelj** [comment] 2021-12-08 12:55
The code behind this is quite complicated -- not something I can easily pull out. This video shows what's happening:

https://user-images.githubusercontent.com/2777107/145210685-e807e30e-493e-439b-9ec9-8596ffd5ed71.mp4

At the point it stops, it should be selecting the "Playlists" tab.
In case it is useful:

![image](https://user-images.githubusercontent.com/2777107/145211601-a15ec4ca-8085-459c-9c6d-b6033348cd30.png)

I am indeed able to execute this manually. These tests have been stable for a long time across multiple Detox versions so I'm confident there's no issue there (as mentioned, I get a full clean pass on 19.2.0).

**Comment by asafkorem** [comment] 2021-12-08 13:15
@Vannevelj thanks, this wasn't very useful however. I must have more information in order to help you..
What's the failing action? What are you trying to tap? it says `RCTImageView` in the error message.. is the "playlists" button is the image view?
Do you have more than one scene in your app?

It appears that Detox is unable to hit the target view. Can you check which view is the hitten?
> Hitten: <UIView: 0x7fa90e910b90; frame = (0 0; 1024 1366); autoresize = W+H; layer = <CALayer: 0x600000d31320>>

**Comment by asafkorem** [comment] 2021-12-08 13:15
> These tests have been stable for a long time across multiple Detox versions so I'm confident there's no issue there (as mentioned, I get a full clean pass on 19.2.0).

As I already mentioned, the latest version changed the implementation of our actions in a way that we are stricter on the check whether a view is hittable. If it didn't failed before, it doesn't mean that your test / code is valid.
However, since you're saying that you are able to execute this manually, that's an issue indeed.

**Comment by Vannevelj** [comment] 2021-12-08 17:12
> Do you in case have more than one key window in your app?

I'm not as familiar with native iOS development. We have a relatively basic native layer as well as a react-navigation layer that nests a few stacks (5 screens: NoAccess, Login, Session List, Settings & Video Player). In the Video player we have a sidebar stack that has three tabs ("Playlists" and "Instances" are in there, which is what is shown in the test). Each of these tabs then has a `FlatList` of items (e.g. a list of playlists) and if you select an item, it will navigate you to another view with a `FlatList` (the clips within a specific playlist).
 
> It appears that Detox is unable to hit the target view. Can you check which view is the hitten?
> 
> > Hitten: <UIView: 0x7fa90e910b90; frame = (0 0; 1024 1366); autoresize = W+H; layer = <CALayer: 0x600000d31320>>

How would I go about checking this?

**Comment by asafkorem** [comment] 2021-12-09 09:19
> How would I go about checking this?

You can [debug in Xcode while running detox tests](https://wix.github.io/Detox/docs/guide/debugging-in-xcode/), copy the hex address of the view to the filter field at the navigator pane when examining the view hierarchy in Xcode (Debug View Hierarchy):
![image](https://user-images.githubusercontent.com/55082339/145367401-ebafa55b-51f6-4652-89c9-6e7db508d6eb.png)

Maybe a more simple alternative, without running detox tests, you can locate the view in the view hierarchy by its frame (`.. = (0 0; 1024 1366)`), this information should be available in the right pane when debugging the view hierarchy (under "Description").
![image](https://user-images.githubusercontent.com/55082339/145368353-3f694a3b-dfe6-4435-b679-ca06390f0582.png)

However, you may have more than one view with these bounds..

**Comment by asafkorem** [comment] 2021-12-09 09:23
Also, please provide here the hierarchy of the target view. You can locate it also using its "Accessibility" properties on the right pane (in your case, `value = Playlists`).
![image](https://user-images.githubusercontent.com/55082339/145369073-e142c043-a0b5-4f8f-8daf-c650254d3c8f.png)

**Comment by d4vidi** [comment] 2021-12-12 13:09
Hi @Vannevelj. Really sorry this change has affected you in this way. We've put in serious efforts into thinking whether there ought to be use cases out there where tests could break because of this. That's the reason we're asking for more and more info from your side - so we could analyze and put them into consideration. We'd really appreciate your cooperation.

Let's try to bear in mind that, all in all, this _really is_ for the better.

**Comment by Vannevelj** [comment] 2021-12-12 13:43
Hey @asafkorem @d4vidi -- no worries, I totally understand more information is needed. I don't have much time left until the holiday break so unfortunately Detox 19.3.0 has taken a backseat compared to other work. I'll try to provide the info you asked for but at least this thread is out there for others to chime in if they see the same thing. I fully appreciate the work you've put into Detox, it's made my life a lot easier.

**Comment by asafkorem** [comment] 2021-12-23 10:20
@Vannevelj 
Can you please try to add the target button a `testID` and access the button element it by its ID (and not by its text)?

**Comment by avanderberg** [comment] 2021-12-23 20:52
I get the same error when I execute a test with Detox version 19.3.1:

```
    DetoxRuntimeError: Test Failed: View is not hittable at its visible point. Error: Failed to hit view at point {187.5, 136.5} with `hitTest`.
    - Origin view: <UIView: 0x7fe16d0d7320; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x600000da0500>>
    - Absolute origin: {0, 0}
    - Hitten: <UIView: 0x7fe16d0d7320; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x600000da0500>>
    - Target view: <RCTView: 0x7fe16d1fda90; reactTag: 2043; frame = (0 0; 375 44); layer = <CALayer: 0x600000d8c760>>
    - Relative point: {187.5, 136.5}
```

I get the issue after this screen is displayed:
![Simulator Screen Shot - iPhone 8 - 2021-12-23 at 20 18 06](https://user-images.githubusercontent.com/215668/147290382-db5c9c11-1550-4a3d-854f-75d8f5dcb89f.png)


The steps the Detox test executes are:
- open this Security screen
- tap on the link "Unpair your device"
- tap on "Cancel" (see screenshot), this closes the dialog
- tap on the link "Unpair your device" again. This step fails with the DetoxRuntimeError above.

I notice that after the tap on Cancel that closes the dialog, the app does not react to the first tap on the Security screen. Only a second tap on the "Unpair your device" link opens the dialog again.
I can reproduce this behavior when I tap with my mouse manually.

The test works fine with Detox version 18.23.1. When I use this old  version, then tapping manually works fine as well.

Android is not affected by this issue.

I use 
- React Native: 0.65.1
- Node: 14.18.2
- Device: iPhone 8 simulator
- Xcode: 13.2.1
- iOS: 15.2
- macOS: 12.1
- Test-runner (select one): jest-circus

**Comment by asafkorem** [comment] 2021-12-23 20:59
Thanks @avanderberg, I understand the issue you're having and I'm able to reproduce this. 
I'm working on a fix for this bug 🙂

**Closed** 2021-12-27 11:55 UTC
Labels: z_platform: ios, type: triage/bug

**Comment by Vannevelj** [comment] 2022-01-04 14:34
> @Vannevelj Can you please try to add the target button a `testID` and access the button element it by its ID (and not by its text)?

Sorry for the delayed response, I'm back in the office now. The test as it was already targetted via the `testID`.
I've just given it a try and bumping my test suite to 19.4.1 passes without an issue -- I know you've reverted the changes but just wanted to pass that on.

**Comment by asafkorem** [comment] 2022-01-04 16:02
@Vannevelj Thanks for the update!

**Comment by christianrank** [comment] 2022-11-22 13:01
I see the same error also on Detox 20.0.1.

After closing an alert on iOS, I can't tap on anything anymore.

So it looks like it is broken again.

```
   Test Failed: View is not hittable at its visible point. Error: Failed to hit view with identifier `doSearch` at point {194.99999237060547, 714.33334350585938} with hit-test
    - Origin view: <UIView: 0x7f9e50b24db0; frame = (0 0; 390 844); autoresize = W+H; layer = <CALayer: 0x6000004c50a0>>
    - Absolute origin: {0, 0}
    - Hitten: <UIView: 0x7f9e50b24db0; frame = (0 0; 390 844); autoresize = W+H; layer = <CALayer: 0x6000004c50a0>>
    - Target view: <RCTView: 0x7f9e4ffa1870; reactTag: 5085; frame = (69.3333 20; 251.333 51.3333); backgroundColor = UIExtendedSRGBColorSpace 0.0117647 0.6 0.890196 1; layer = <CALayer: 0x6000004dd0a0>>
    - Relative point: {194.99999237060547, 714.33334350585938}
```

**Comment by Saad-Bashar** [comment] 2022-11-24 13:51
Not sure what happened, ours one was working fine just few days back. But now I am getting the same error that my login button is not view is not hittable.

**Comment by d4vidi** [comment] 2022-11-27 12:16
Apologies for the inconvenience, but this change was mandatory, and was merely postponed until the issue is Fixed in React Native itself, first (i.e. in version `.67.1`).
Mind the documentation in the [v19.13.0 release notes](https://github.com/wix/Detox/releases/tag/19.13.0).

**Comment by gabrieldonadel** [comment] 2022-11-30 20:02
@d4vidi It seems that this new hittability-check mechanism is incompatible with `FullWindowOverlay` from react-native-screens. 

I'm currently using
```
"react-native": "0.69.7",
"react-native-screens": "^3.18.2",
 "detox": "^20.0.3"
```

**Comment by jeffFG** [comment] 2023-06-29 11:05
seem this bug is still not fixed over half year ?

**Comment by ayelenguini** [comment] 2023-07-27 17:45
This is still an issue in RN `0.72.2` and Detox `20.7.0`. Could we maybe have some different threshold points to choose from so we could still tap on the tabs on React Navigation? @asafkorem

**Comment by iacovlev-pavel** [comment] 2023-07-27 18:00
I use UI Kitten, and all the components that use React Native Modal like Popover or Select fail the hit test in Detox 20, while passing in Detox 19.
The core issue is the Modal has a backdrop, and I am not able to click on the backdrop to dismiss the Modal in Detox 20.

Modal component:
https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/theme/backdrop/backdrop.component.tsx#L52

Backdrop component:
https://github.com/akveo/react-native-ui-kitten/blob/master/src/components/theme/backdrop/backdrop.component.tsx

**Comment by bemaverick** [comment] 2023-08-04 11:01
i've faced the same issue. Any updates?

**Comment by joshuanatanielnm** [comment] 2023-11-16 22:37
any update for this issue?
