### ISSUE TITLE
Adding both `detox` and `detox-cli` into the package breaks detox commands

### ISSUE THREAD

**Issue by SeriousBug** [wix/Detox#3425] opened 2022-05-28 04:51 UTC
### Describe your idea

If you add both `detox` and `detox-cli` into a package:

```sh
npm install detox detox-cli --save-dev
```

Then running any detox command causes it to go into an infinite loop as it repeatedly relaunches itself, as the `detox-cli` overwrites the `node_modules/.bin/detox` binary for `detox`.

I'm not sure if there's a good technical fix for this, but it might be good to call it out in the getting started documentation that `detox-cli` should never be added to the package.

**Comment by noomorph** [comment] 2022-05-28 11:47
@SeriousBug duplicate of https://github.com/wix/Detox/issues/2750 . Make sure to vote up 👍  the issue.

Actually, there was a fix for it, but the library we relied on – it had issues on Windows machines, if I'm not mistaken, so we decided to leave it as is.

P. S. We might return to it on one of bugathons, @d4vidi

**Closed by noomorph** 2022-05-28 11:47 UTC
Labels: type: enhancement ⚡️, status: triage
