### ISSUE TITLE
Windows 10 android runs do not start on a android emulator

### ISSUE THREAD

**Issue by MaverickFromSpartan** [wix/Detox#2209] opened 2020-07-14 12:47 UTC
**Describe the bug**
On windows 10 with detox 17.1.1 I can't run a detox test on an android emulator

**To Reproduce**

- [yes] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:

I created my configuration
```
    "android": {
      "type": "android.emulator",
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "build": "cd android && gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
      "device": {
        "avdName": "Pixel_2_API_28"
      }
    },
```
I ran my build command: detox build --configuration android
I started the detox test: detox test --configuration android

**Expected behavior**
The detox test should complete without issue

**Device and Verbose Detox Logs**
```
detox[17996] ERROR: [exec.js/EXEC_FAIL, #14] ""G:\Work\AndroidSettings\platform-tools\adb.EXE" -s emulator-14142 push "G:\Work\GitRepos\LegionellaMobile\environmental-client\android\app\build\outputs\apk\debug\app-debug.apk" "\data\local\tmp\detox\Application.apk"" faile
d with code = 1, stdout and stderr:

detox[17996] ERROR: [exec.js/EXEC_FAIL, #14] adb: error: failed to copy 'G:\Work\GitRepos\LegionellaMobile\environmental-client\android\app\build\outputs\apk\debug\app-debug.apk' to '\data\local\tmp\detox\Application.apk': remote couldn't create file: Read-only file system
G:\Work\GitRepos\LegionellaMobile\environmental-client\android\app\build\outputs\apk\debug\app-debug.apk: 1 file pushed, 0 skipped. 321.0 MB/s (41025844 bytes in 0.122s)

detox[17996] ERROR: [exec.js/EXEC_FAIL, #14]
detox[17996] ERROR: ChildProcessError: Command failed: "G:\Work\AndroidSettings\platform-tools\adb.EXE" -s emulator-14142 push "G:\Work\GitRepos\LegionellaMobile\environmental-client\android\app\build\outputs\apk\debug\app-debug.apk" "\data\local\tmp\detox\Application.apk"
 `"G:\Work\AndroidSettings\platform-tools\adb.EXE" -s emulator-14142 push "G:\Work\GitRepos\LegionellaMobile\environmental-client\android\app\build\outputs\apk\debug\app-debug.apk" "\data\local\tmp\detox\Application.apk"` (exited with error code 1)
detox[17996] INFO:  Example is assigned to undefined
detox[17996] INFO:  Example: should have welcome screen
detox[17996] INFO:  Example: should have welcome screen [SKIPPED]

detox[7304] ERROR: [cli.js] Error: Command failed: node_modules\.bin\jest --config e2e/config.json "--testNamePattern=^((?!:ios:).)*$" --maxWorkers 1 e2e

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Environment (please complete the following information):**
 - Detox: 17.1.1
 - React Native:
    "react": "~16.11.0",
    "react-native": "~0.62.2",
 - Node: 14.3.0
 - Device: Android simulator
 - OS: Windows 10
 - Test-runner (select one): `jest-circus`

**Comment by noomorph** [comment] 2020-07-14 18:07
Duplicate of #2178.

**Closed by noomorph** 2020-07-14 18:07 UTC
Labels: type: triage/bug, z_platform: android
