### ISSUE TITLE
Module detox/runners/jest/globalSetup in the globalSetup option was not found

### ISSUE THREAD

**Issue by sergibondarenko** [wix/Detox#3771] opened 2022-12-20 14:40 UTC
### Description

I follow the [guide](https://wix.github.io/Detox/docs/introduction/getting-started) and when I execute the tests `detox test --configuration ios.sim.debug` I get the following error. Why?

```
✗ detox test --configuration ios.sim.debug
15:35:31.587 detox[14960] B jest --config jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

15:35:31.690 detox[14960] E Command failed with exit code = 1:
jest --config jest.config.js
```

Jest config
```
✗ cat jest.config.js 
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  rootDir: '..',
  testMatch: ['<rootDir>/e2e/**/*.test.js'],
  testTimeout: 120000,
  maxWorkers: 1,
  globalSetup: 'detox/runners/jest/globalSetup',
  globalTeardown: 'detox/runners/jest/globalTeardown',
  reporters: ['detox/runners/jest/reporter'],
  testEnvironment: 'detox/runners/jest/testEnvironment',
  verbose: true,
}
```

Path to the detox module
```
✗ ls node_modules/detox/runners/jest
JestCircusEnvironment.js adapter.js               assignReporter.js        globalTeardown.js        index.js                 reporters                specReporter.js          testEnvironment
adapter.d.ts             assignReporter.d.ts      globalSetup.js           index.d.ts               reporter.js              specReporter.d.ts        streamlineReporter.js
```

### Your environment

Detox version: 20.1.0
React Native version: 0.64.0 
Node version: 16.15.0 
Device model: - 
OS: macOS Ventura 13.1
Test-runner (select one): jest

**Comment by noomorph** [comment] 2022-12-20 15:53
Hmm, maybe it is somehow related to `rootDir: ..`. Are you sure that is correct?

**Comment by sergibondarenko** [comment] 2023-01-04 15:43
> Hmm, maybe it is somehow related to `rootDir: ..`. Are you sure that is correct?

Yes, I'm sure it is correct. Besides the validation error displays it `<rootDir> is: /Users/user/Development/app` The user name is `user`.

**Comment by noomorph** [comment] 2023-01-04 15:59
Looks like you are running it from `app/e2e` folder as a working directory. Could you run it from the `/Users/user/Development/app` e.g. `npx detox test --configuration ios.sim.debug`?

**Comment by sergii-bo** [comment] 2023-01-04 16:13
> npx detox test --configuration ios.sim.debug

I run it from the root of the app.

```zsh
➜  app git:(try-detox) ✗ pwd
/Users/user/Development/aproject/playground/app
➜  app git:(try-detox) ✗ npx detox test --configuration ios.sim.debug
17:08:42.190 detox[98875] B jest --config e2e/jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/aproject/playground/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

17:08:42.355 detox[98875] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

➜  app git:(try-detox) ✗ detox test --configuration ios.sim.debug 
17:09:02.907 detox[98940] B jest --config e2e/jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/aproject/playground/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

17:09:03.005 detox[98940] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

➜  app git:(try-detox) ✗ ./node_modules/.bin/detox test --configuration ios.sim.debug
17:09:13.943 detox[98989] B jest --config e2e/jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/aproject/playground/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

17:09:14.040 detox[98989] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

➜  app git:(try-detox) ✗ ls node_modules/detox
Detox-android     Detox-ios.tbz     README.md         detox-native      index.js          internals.js      node_modules      runners           src
Detox-ios-src.tbz LICENSE           android           index.d.ts        internals.d.ts    local-cli         package.json      scripts           tsconfig.json

```

**Comment by sergibondarenko** [comment] 2023-01-04 16:15
> Looks like you are running it from `app/e2e` folder as a working directory. Could you run it from the `/Users/user/Development/app` e.g. `npx detox test --configuration ios.sim.debug`?

> npx detox test --configuration ios.sim.debug

I run it from the root of the app.

```zsh
➜  app git:(try-detox) ✗ pwd
/Users/user/Development/aproject/playground/app
➜  app git:(try-detox) ✗ npx detox test --configuration ios.sim.debug
17:08:42.190 detox[98875] B jest --config e2e/jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/aproject/playground/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

17:08:42.355 detox[98875] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

➜  app git:(try-detox) ✗ detox test --configuration ios.sim.debug 
17:09:02.907 detox[98940] B jest --config e2e/jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/aproject/playground/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

17:09:03.005 detox[98940] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

➜  app git:(try-detox) ✗ ./node_modules/.bin/detox test --configuration ios.sim.debug
17:09:13.943 detox[98989] B jest --config e2e/jest.config.js
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.
         <rootDir> is: /Users/user/Development/aproject/playground/app

  Configuration Documentation:
  https://jestjs.io/docs/configuration

17:09:14.040 detox[98989] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

➜  app git:(try-detox) ✗ ls node_modules/detox
Detox-android     Detox-ios.tbz     README.md         detox-native      index.js          internals.js      node_modules      runners           src
Detox-ios-src.tbz LICENSE           android           index.d.ts        internals.d.ts    local-cli         package.json      scripts           tsconfig.json

```

**Comment by noomorph** [comment] 2023-01-06 11:44
DM'ed you, @sergibondarenko .

**Comment by noomorph** [comment] 2023-01-16 14:21
Closing as there is not enough information to reproduce. Unfortunately, it is not possible to remote-debug this at the moment.

**Closed by noomorph** 2023-01-16 14:21 UTC
Labels: user: more info needed

**Comment by AbdullahJubayer-LS** [comment] 2023-03-09 16:36
Hi, I am seeing a similar issue and wondering if there was a solution...

`11:33:05.873 detox[4991] B jest --config e2e/jest.config.js --debug
● Validation Error:

  Module detox/runners/jest/globalSetup in the globalSetup option was not found.`

Few package(s) version for our app: 
    "react": "^18.2.0",
    "react-native": "0.69.7",
    "detox": "^20.4.0",
    "jest": "^29.4.3"

**Comment by amrlabib** [comment] 2023-08-21 14:07
updating `graceful-fs` version fixed the issue for me

**Comment by noomorph** [comment] 2023-08-21 15:19
Oh, these packager manager issues are hard to spot from issue descriptions.
