### ISSUE TITLE
Log artifacts is empty.

### ISSUE THREAD

**Issue by rawqing** [wix/Detox#1326] opened 2019-04-23 04:17 UTC
I use `detox test --configuration ios.sim.release --debug-synchronization --take-screenshots all --record-logs all` running detox test example app with `jest`, `test.log` artifacts always empty.
![image](https://user-images.githubusercontent.com/18608327/56553666-c897dd00-65c1-11e9-87a3-e6a893de7056.png)

**Comment by noomorph** [comment] 2019-04-23 08:39
This is expected — the current implementation of collection device logs in iOS is not verbose, so many of the logs are indeed empty. Please check, for example, logs for `Actions should type in an element`:

<img width="640" alt="Actions should type in an element" src="https://user-images.githubusercontent.com/1962469/56566765-1d385980-65bc-11e9-9995-41da3c151b88.png">

If it is empty, let's see how we can reproduce your situation.

**Comment by rawqing** [comment] 2019-04-23 10:23
@noomorph  Hello, there is no special way，it always appears.
package.json:
```
{
  "name": "detox-test",
  "version": "12.4.0",
  "private": true,
  "scripts": {
    "test": ":",
    "packager": "react-native start",
    "detox-server": "detox run-server",
    "e2e:ios": "detox test --configuration ios.sim.release --debug-synchronization --take-screenshots all --record-logs all",
    "e2e:android": "detox test --configuration android.emu.release --take-screenshots all --record-logs all",
    "build:ios": "detox build --configuration ios.sim.release",
    "build:android": "detox build --configuration android.emu.release",
    "verify-artifacts:ios": "jest ./scripts/verify_artifacts_are_not_missing.ios.test.js --testEnvironment node",
    "verify-artifacts:android": "jest ./scripts/verify_artifacts_are_not_missing.android.test.js --testEnvironment node"
  },
  "dependencies": {
    "moment": "^2.24.0",
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "detox": "^12.4.0",
    "express": "^4.15.3",
    "lodash": "^4.14.1",
    "mocha": "^6.1.3"
  },
  "detox": {
    "test-runner": "jest",
    "runner-config": "e2e/config.json",
    "__session": {
      "server": "ws://localhost:8099",
      "sessionId": "test"
    },
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/example.app",
        "build": "set -o pipefail && xcodebuild -project ios/example.xcodeproj -UseNewBuildSystem=NO -scheme example_ci -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build | xcpretty",
        "type": "ios.simulator",
        "name": "iPhone X"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/example.app",
        "build": "set -o pipefail && export CODE_SIGNING_REQUIRED=NO && export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -project ios/example.xcodeproj  -UseNewBuildSystem=NO -scheme example_ci -configuration Release -sdk iphonesimulator -derivedDataPath ios/build | xcpretty",
        "type": "ios.simulator",
        "name": "iPhone 7 Plus"
      },
      "ios.none": {
        "binaryPath": "ios",
        "type": "ios.none",
        "name": "iPhone X",
        "session": {
          "server": "ws://localhost:8099",
          "sessionId": "com.wix.detox-example"
        }
      },
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/fromBin/debug/app-fromBin-debug.apk",
        "build": "cd android && ./gradlew assembleFromBinDebug assembleFromBinDebugAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_26"
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/fromBin/release/app-fromBin-release.apk",
        "build": "cd android && ./gradlew assembleFromBinRelease assembleFromBinReleaseAndroidTest -DtestBuildType=release && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_26"
      },
      "android.emu.debug.fromSource": {
        "binaryPath": "android/app/build/outputs/apk/fromSource/debug/app-fromSource-debug.apk",
        "build": "cd android && ./gradlew assembleFromSourceDebug assembleFromSourceDebugAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_26"
      }
    }
  }
}
```
e2e/config.json:
```
{
  "setupTestFrameworkScriptFile": "./init.js",
  "testEnvironment": "node",
  "testMatch": ["**/e2e/02.matchers.test.js"]
}
```
e2e/init.js:
```
const detox = require('detox/src/index');
const config = require('../package.json').detox;
const adapter = require('detox/runners/jest/adapter');

jest.setTimeout(120000);
jasmine.getEnv().addReporter(adapter);

beforeAll(async () => {
  try {
    await detox.init(config);
  } catch (e) {
    await detox.cleanup();
    await new Promise(resolve => setTimeout(resolve, 1000));
    process.exit(1);
  }
});

beforeEach(async function () {
  await adapter.beforeEach(this);
});


afterAll(async () => {
  await detox.cleanup();
});

process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
});
```
run script:
`npm run e2e:ios`

test case path:  detox/test/e2e/02.matchers.test.js ( I use detox test example ：you can find it https://github.com/wix/Detox/blob/master/detox/test/e2e/02.matchers.test.js ）

**Comment by noomorph** [comment] 2019-04-23 10:28
If it always appears, what's the problem then?

Do you want empty logs to not appear in the folders? I'm not sure this makes sense but we can discuss this change to the behavior.

Please be more specific.

**Comment by rawqing** [comment] 2019-04-23 10:45
In my opinion, this `test.log` file should be logged correctly, not left blank.
The log output from the console is useful for every test case,we can see the reason for the failure from this, Instead of looking at the output in the terminal.

**Comment by noomorph** [comment] 2019-04-25 06:24
@rawqing, I have three theses on the issue you have created:

0. The behavior you describe was expected. Hence it is not a bug. On the other hand, your narrative contains two separate feature requests.
1. You ask to hijack into test runner log subsystem (be it Mocha, Jest, Ava, Tape or whatever) so Detox pipes everything to logs. This request seems reasonable, albeit we have yet to investigate how feasible the generic solution is, in this case.
2. You suggest cutting a continuous `detox_<pid>.log` into numerous pieces distributed across the folders with the corresponding test names. I might agree that the current way of keeping test session logs is not always convenient, but a dismemberment, if made unconditional, seems controversial too, as it is apt to complicate following a timeline of events that were happening during an entire test run. So, if this feature gathers enough proponents, I think we can solve via adding advanced configuration options to log artifacts subsystem... something like:

```typescript
type DetoxConfiguration = {
  /* ... */

  artifacts?: {
    /* ... */

    log?: {
      mode?: 'none' | 'failing' | 'all';
      runnerLoggingStrategy?: 'single-file' | 'by-process' | 'by-test';
      formatter?: 'json' | 'plain';
    };
  };
};
```

Consequently:

* In the light of (0), I will close this issue as it is clearly not a bug, but feature request(s).
* I recommend you to create two feature requests according to (1) and (2), or whatever you think is appropriate — maybe I've missed some of lacking features you consider to be necessary.

Thanks for your application. I hope your grievances get a resolution in the foreseeable future.

**Closed by noomorph** 2019-04-25 06:24 UTC
Labels: platform: ios, type: triage/bug
