### ISSUE TITLE
Detox tests are flaky in CI

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#126] opened 2017-05-16 16:18 UTC
>Error: no test specified
>lerna ERR! test Errored while running script in 'detox'
>lerna ERR! execute Error: Command failed: npm run test

The documentation is updated, and builds are failing randomly.

**Comment by talkol** [comment] 2017-05-17 22:18
This is referring to detox's own test suite.. flakiness is probably due to unresponsive simulators launches on Travis. We should work on improving this.. maybe check if this happened and retry?

**Comment by rotemmiz** [comment] 2017-05-24 21:35
I managed to reproduce this locally. Seems like the issue was that the test project had both `Detox.framework` linked and had it injected in runtime with `FBSIMCTL_CHILD_DYLD_INSERT_LIBRARIES`, causing it to crash in startup and hang the tests (this actually had no affect on users).

We've made the necessary changes, [this is the last commit](https://github.com/wix/detox/commit/20224b835856837052d4e25f8cb1c57cb6cc9042) which completes the fix for this.

**Closed** 2019-05-16 09:25 UTC
