### ISSUE TITLE
matcher fails without `atIndex` or `atIndex(1)`, and pass with `atIndex(0)`

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#4126] opened 2023-07-12 14:41 UTC
### What happened?

See internal support case ([#181](https://github.com/wix-private/detox/issues/201)) by @bunkib: https://wix.slack.com/archives/C1Y4D9BK8/p1688999806178809

Fails without `atIndex` (`multiple views in the hierarchy`):
![image](https://github.com/wix/Detox/assets/55082339/1594240c-8863-439e-ac56-0bacb371577c)

Fails with `atIndex(1)`:
![image](https://github.com/wix/Detox/assets/55082339/e9b34b30-4c82-4ba6-84b2-5b0be80f6ea8)

### What was the expected behaviour?

Pass without `atIndex` or have more than one element available.

**Comment by d4vidi** [comment] 2023-07-13 10:04
@bunkib so this use case normally works on Android... is there anything noticeably special about the view hierarchy in the screen you're checking?

**Comment by d4vidi** [comment] 2023-10-26 09:47
So just to clarify, there are in fact 2 problems involved:
1. The issue of `getAttributes()` not working with multiple matches. This was directly resolved in #3196.
2. The failed matching in the `atIndex(1)` case, while allegedly two matching items exist in the view hierarchy.

**Comment by d4vidi** [comment] 2023-10-26 11:48
As I can't reproduce problem 2 (the case with `atIndex(1)`) - I'm closing the issue. Perhaps @ArtiomBodilovski could shed more light on this in the future.

What I've tried doing:
- Though from iOS, a view-hierarchy snapshot artifact shows that the matched-for items were out of screen bounds.
- I therefore tried mimicking this use case based on our self-test project's Matchers screen, with the `Index` elements set beyond the screen's bottom. As far as this specific is concerned, things seems to work well (i.e. `getAttributes()` works for whatever's in the view hierarchy, regardless of screen bounds).
- I also _did_ try to set the Matchers-screen's `Index` elements under a scrollable flat list. `atIndex()` still seems to be working well.

**Closed by d4vidi** 2023-10-26 11:48 UTC
Labels: type: bug 🐞, platform: android, status: accepted
