### ISSUE TITLE
Mocha 4.0.0 doesn't exit after running tests

### ISSUE THREAD

**Issue by maartenschumacher** [wix/detox#398] opened 2017-11-10 10:34 UTC
#### Description

While following the Getting Started guide I pulled the latest version of Mocha, which doesn't exit the process after completing the tests (https://github.com/mochajs/mocha/releases/tag/v4.0.0, you can revert to the old behavior by passing a `--exit` flag to the mocha run command). However it took me a while to realize this and thought something was wrong with detox. I had to run the example project to finally understand I had a newer version of mocha.

Maybe you should migrate to the new mocha version, passing the `--exit` flag in the default mocha.opts? Or declare a peer dependency of mocha 3? Not sure about the best way to handle this.

#### Steps to Reproduce

Upgrade mocha to the latest version in the example project and run the tests; it seems to just hang after completing the tests.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.3
* Node: 8.7.0
* Device: iPhone 7 Plus, iOS 11.1
* Xcode: 9.1
* macOS: 10.13

#### Device and verbose Detox logs

na

**Comment by LeoNatan** [comment] 2017-11-12 09:57
This is a duplicate of another issue. Please use the search function before opening new issues.

**Closed by LeoNatan** 2017-11-12 09:57 UTC

**Comment by ChrisGrigg** [comment] 2018-01-18 00:14
What's the duplicate? Care to share a link?

**Comment by rotemmiz** [comment] 2018-01-18 06:57
It was fixed about two months ago, use Detox 6.x.x for latest fixes and features. And read the release notes for breaking changes.

https://github.com/wix/detox/issues/368
