### ISSUE TITLE
Swipe Action Doesn't Work on RN ListView?

### ISSUE THREAD

**Issue by aarongreenwald** [wix/detox#103] opened 2017-03-30 10:07 UTC
See [this commit](https://github.com/wix/react-native-chat-listview/commit/fe90e6298cab5dde8543ca450ffbe618f1ff5263) - the test in question fails because it doesn't execute the swipe. Or at least I don't see it happen in the simulator when I'm running locally.

The test output: 

```
1) sanity e2e should see more messages after scrolling:
     Error: Cannot find UI Element.
Exception with Assertion: {
  "Assert Criteria" : "assertWithMatcher: matcherForSufficientlyVisible(>=0.750000)",
  "Element Matcher" : "(((respondsToSelector(accessibilityIdentifier) && accessibilityID('0')) && !kindOfClass('RCTScrollView')) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(accessibilityIdentifier) && accessibilityID('0')) && kindOfClass('RCTScrollView'))))))",
  "Recovery Suggestion" : "Check if element exists in the UI, modify assert criteria, or adjust the matcher"
}

Error Trace: [
  {
    "Description" : "Interaction cannot continue because the desired element was not found.",
    "Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Code" : "0",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
    "Line" : "142"
  }
]
```

When I had it as a simple scrollview in the [source](https://github.com/wix/react-native-chat-listview/blob/fe90e6298cab5dde8543ca450ffbe618f1ff5263/demo/demo-app.component.js#L32), not a listview, the swipe worked.

**Comment by LeoNatan** [comment] 2017-06-06 19:35
Does this still reproduce on modern RN and Detox?

**Comment by rumax** [comment] 2017-06-12 06:51
@LeoNatan ScrollView works fine for me except the case if you have nested ScrollView. See this change to the demo: https://github.com/rumax/detox/commit/ce3596ca0978df60a0875c47170b0919bbfd4e3e

Log:
```
detox info 5: com.wix.demo.react.native launched 
  Example
    ✓ should have welcome screen (793ms)
    ✓ should show hello screen after tap (364ms)
    ✓ should show world screen after tap (360ms)
    1) should be visible


  3 passing (15s)
  1 failing

  1) Example should be visible:
     Error: Multiple UI elements matched for given criteria.
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher: matcherForSufficientlyVisible(>=0.750000)",
  "Element Matcher" : "(((respondsToSelector(accessibilityIdentifier) && accessibilityID('vScrollView')) && !kindOfClass('RCTScrollView')) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(accessibilityIdentifier) && accessibilityID('vScrollView')) && kindOfClass('RCTScrollView'))))))",
  "Recovery Suggestion" : "Create a more specific matcher to narrow matched element"
}

Error Trace: [
  {
    "Description" : "Multiple elements were matched: (
    "<RCTCustomScrollView:0x7f85bb091000; AX=N; AX.frame={{0, 0}, {414, 736}}; AX.activationPoint={207, 368}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 736}}; opaque; alpha=1>",
    "<RCTCustomScrollView:0x7f85ba833a00; AX=N; AX.frame={{0, 154}, {414, 100}}; AX.activationPoint={207, 204}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 100}}; opaque; alpha=1>"
). Please use selection matchers to narrow the selection down to single element.",
    "Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Code" : "5",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction grey_errorForMultipleMatchingElements:withMatchedElementsIndexOutOfBounds:]",
    "Line" : "910"
  }
]
     
```

If I remove `<ScrollView horizontal testID="hScrollView">` from demo, it works fine.

**Comment by Lowry99** [comment] 2017-09-13 14:32
Hey guys, 

Like to report that this still replicates.
My component is looking something like this 

```
 render() {
    if (this.props.data.loading) {
      return (
        <View style={styles.Container}>
          <ActivityIndicator size={"large"} />
        </View>
      );
    }

    this.state = {
      dataSource: ds.cloneWithRows(
        ArticlePage.prepareDataForListView(this.props)
      )
    };
    return (
      <View testID='articleWrapper' style={styles.PageWrapper}>
        <ListView
          testID="listView"
          dataSource={this.state.dataSource}
          renderRow={ArticlePage.renderRow}
          initialListSize={10}
          scrollRenderAheadDistance={10}
          pageSize={1}
        />
      </View>
    );
  }
```

If I attempt to use any of the detox actions involving a `swipeView`
such as 
`await element(by.id('scrollView')).swipe('down');` 

I am presented with 
```
Cannot find UI element.
    Exception with Action: {
      "Action Name" : "Scroll To Bottom content edge",
      "Element Matcher" : "(((((kindOfClass('UIScrollView') || kindOfClass('UIWebView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('listView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('listView')))))) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((((kindOfClass('UIScrollView') || kindOfClass('UIWebView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('listView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('listView')))))) && kindOfClass('RCTScrollView'))))))",
      "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
    }

    Error Trace: [
      {
        "Description" : "Interaction cannot continue because the desired element was not found.",
        "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code" : "0",
        "File Name" : "GREYElementInteraction.m",
        "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
        "Line" : "121"
      }
    ]

      at Invoke._callee5$ (node_modules/detox/lib/client/actions/actions.js:74:52)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:337:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:96:21)
      at step (node_modules/detox/lib/client/actions/actions.js:1:836)
      at node_modules/detox/lib/client/actions/actions.js:1:1066
      at new Promise (node_modules/core-js/modules/es6.promise.js:177:7)
      at Invoke.<anonymous> (node_modules/detox/lib/client/actions/actions.js:1:747)
      at Invoke.handle (node_modules/detox/lib/client/actions/actions.js:77:229)
      at Client._callee9$ (node_modules/detox/lib/client/Client.js:59:26)
```

Let me know if I can be of any more help
`  "react-native": "0.42.3",`
` "detox": "5.1.3",`

**Comment by Lowry99** [comment] 2017-09-13 14:32
just seen there are new versions of detox, will upgrade and get back to you!

**Comment by Lowry99** [comment] 2017-09-13 15:51
So this half works

The component scrolls but on the Warning overlay shown below.
Not sure if this is a detox issue or a react thing

<img width="467" alt="screen shot 2017-09-13 at 16 50 56" src="https://user-images.githubusercontent.com/12037104/30387217-c143f1a2-98a3-11e7-8981-fb8619c3509b.png">

**Comment by Lowry99** [comment] 2017-09-14 13:04
stick in a `console.disableYellowBox = true;` in your app and this works as expected

**Comment by LeoNatan** [comment] 2017-11-21 17:40
This issue seems like a duplicate of #85 which is supposed to be fixed in Earl Grey. Just to make sure, with the latest versions of Detox, do you still reproduce this when a yellow box is shown?

**Closed** 2018-03-07 19:26 UTC
Labels: user: more info needed
