### ISSUE TITLE
React Native child with zIndex style fails toBeVisible tests

### ISSUE THREAD

**Issue by defualt** [wix/Detox#1314] opened 2019-04-18 16:30 UTC
# **Describe the bug**
There is unexpected failure of `.toBeVisible()` tests under this set of conditions
- A parent `View` has a `testID` attribute.
- That `testID` is used to select that parent `View` for the `.toBeVisible()` test.
- That parent `View` has a child `View`.
- That child `View` has `zIndex` style assigned to it.

Child height and width relative to the parent height and width change the success/failure results of the `.toBeVisible()` test.  Various configurations and results described below.

# **To Reproduce**

- [ x] I have tested this issue on the latest Detox release and it still reproduces

## Test condition

```
await expect(element(by.id("findme"))).toBeVisible();
```

## No zIndex, PASSES

```
<View
  testID="findme"
  style={{width:100,height:100,backgroundColor:'red'}}
>
  <View
    style={{width:100,height:100,backgroundColor:'green'}}
  />
</View>
```

## Child has zIndex, FAILS

```
<View
  testID="findme"
  style={{width:100,height:100,backgroundColor:'red'}}
>
  <View
    style={{width:100,height:100,backgroundColor:'green', zIndex:1}}
  />
</View>
```

## Child has zIndex, child width is 25%, PASSES AGAIN

```
<View
  testID="findme"
  style={{width:100,height:100,backgroundColor:'red'}}
>
  <View
    style={{width:'25%',height:100,backgroundColor:'green', zIndex:1}}
  />
</View>
```

## Child has zIndex, child width is 26%, FAILS AGAIN

```
<View
  testID="findme"
  style={{width:100,height:100,backgroundColor:'red'}}
>
  <View
    style={{width:'26%',height:100,backgroundColor:'green', zIndex:1}}
  />
</View>
```

# **Expected behavior**
All of the the scenarios above should pass the `toBeVisible()` test.  But keep in mind that zIndex as a factor in other circumstances would cause elements to overlap one another in a particular way that would affect `toBeVisible()` test.  zIndex is sometimes a factor in visibility, but it shouldn't be in the To Reproduce section above.

# **Environment (please complete the following information):**
 - Detox: 12.3.0
 - React Native: 0.59.4
 - Node: 9.2.0
 - Device: IPhone X Simulator
 - Xcode: 10.2
 - iOS: 12.2
 - macOS: 10.14.4

# **Device and Verbose Detox Logs**
```
detox[15758] WARN:  [test.js] Deprecation warning: "file" and "specs" support will be dropped in the next Detox version.
detox[15758] WARN:  [test.js] Please edit your package.json according to the migration guide: https://wix.to/I0DOAK0
detox[15758] INFO:  [test.js] configuration="ios.sim.debug" loglevel="verbose" artifactsLocation="artifacts/ios.sim.debug.2019-04-18 16-12-47Z" recordLogs="none" takeScreenshots="manual" recordVideos="none" node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' "e2e"
● Deprecation Warning:

  Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.

  Please update your configuration.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

detox[15760] INFO:  [DetoxServer.js] server listening on localhost:62506...
detox[15760] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:62506
detox[15760] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd
detox[15760] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd
detox[15760] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[15760] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone X" --byOS "12.2"
detox[15760] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone X...
detox[15760] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "60692DE6-6298-40DB-9BBB-881D94AC19D1"
detox[15760] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl uninstall 60692DE6-6298-40DB-9BBB-881D94AC19D1 com.ted.TEDMasterclass
detox[15760] DEBUG: [exec.js/EXEC_TRY, #3] Uninstalling com.ted.TEDMasterclass...
detox[15760] DEBUG: [exec.js/EXEC_SUCCESS, #3] com.ted.TEDMasterclass uninstalled
detox[15760] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl install 60692DE6-6298-40DB-9BBB-881D94AC19D1 "/Users/brianephraim/Sites/ted/masterclass-beta/ios/build/Build/Products/Debug-iphonesimulator/masterclass.app"
detox[15760] DEBUG: [exec.js/EXEC_TRY, #4] Installing /Users/brianephraim/Sites/ted/masterclass-beta/ios/build/Build/Products/Debug-iphonesimulator/masterclass.app...
detox[15760] DEBUG: [exec.js/EXEC_SUCCESS, #4] /Users/brianephraim/Sites/ted/masterclass-beta/ios/build/Build/Products/Debug-iphonesimulator/masterclass.app installed
detox[15760] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl terminate 60692DE6-6298-40DB-9BBB-881D94AC19D1 com.ted.TEDMasterclass
detox[15760] DEBUG: [exec.js/EXEC_TRY, #5] Terminating com.ted.TEDMasterclass...
detox[15760] DEBUG: [exec.js/EXEC_SUCCESS, #5] com.ted.TEDMasterclass terminated
detox[15760] DEBUG: [exec.js/EXEC_CMD, #6] /bin/cat /dev/null >/Users/brianephraim/Library/Developer/CoreSimulator/Devices/60692DE6-6298-40DB-9BBB-881D94AC19D1/data/tmp/detox.last_launch_app_log.out 2>/Users/brianephraim/Library/Developer/CoreSimulator/Devices/60692DE6-6298-40DB-9BBB-881D94AC19D1/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/brianephraim/Library/Detox/ios/3379fbf4599b45bcc3fda752955106daefe7d107/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err 60692DE6-6298-40DB-9BBB-881D94AC19D1 com.ted.TEDMasterclass --args -detoxServer ws://localhost:62506 -detoxSessionId 63378d22-6054-f2b3-d7fa-c29c11ab76fd
detox[15760] DEBUG: [exec.js/EXEC_TRY, #6] Launching com.ted.TEDMasterclass...
detox[15760] INFO:  [AppleSimUtils.js] com.ted.TEDMasterclass launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/brianephraim/Library/Developer/CoreSimulator/Devices/60692DE6-6298-40DB-9BBB-881D94AC19D1/data/tmp/detox.last_launch_app_log.{out,err}
detox[15760] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd)
detox[15760] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd
detox[15760] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd
 FAIL  e2e/firstTest.spec.js (9.761s)
  Example
    ✕ should find element (1430ms)

  ● Example › should find element

    Failed: [Error: Error: An assertion failed.
    Exception with Assertion: {
      "Assertion Criteria":  "assertWithMatcher:matcherForSufficientlyVisible(>=0.750000)",
      "Element Matcher":  "((!(kindOfClass('RCTScrollView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('findme'))) || (((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches(kindOfClass('RCTScrollView'))) && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('findme'))))))"
    }


    Error Trace: [
      {
        "Description":  "Assertion with matcher [M] failed: UI element [E] failed to match the following matcher(s): [S]",
        "Description Glossary":    {
          "M":  "matcherForSufficientlyVisible(>=0.750000)",
          "E":  "<RCTView:0x7f8bc2525ca0; AX=N; AX.id='findme'; AX.frame={{0, 0}, {100, 100}}; AX.activationPoint={50, 50}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {100, 100}}; opaque; alpha=1>",
          "S":  "matcherForSufficientlyVisible(>=0.750000)"
        },
        "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code":  "3",
        "File Name":  "GREYAssertions.m",
        "Function Name":  "+[GREYAssertions grey_createAssertionWithMatcher:]_block_invoke",
        "Line":  "75"
      }
    ]

    Hierarchy: <UIWindow:0x7f8bc250a820; AX=N; AX.frame={{0, 0}, {375, 812}}; AX.activationPoint={187.5, 406}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 812}}; opaque; alpha=1>
      |--<RCTRootView:0x7f8bc240a7f0; AX=N; AX.frame={{0, 0}, {375, 812}}; AX.activationPoint={187.5, 406}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 812}}; opaque; alpha=1>
      |  |--<RCTRootContentView:0x7f8bc271d910; AX=N; AX.frame={{0, 0}, {375, 812}}; AX.activationPoint={187.5, 406}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 812}}; opaque; alpha=1>
      |  |  |--<RCTView:0x7f8bc25264f0; AX=N; AX.frame={{0, 0}, {375, 812}}; AX.activationPoint={187.5, 406}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 812}}; opaque; alpha=1>
      |  |  |  |--<RCTView:0x7f8bc2525fb0; AX=N; AX.frame={{0, 0}, {375, 812}}; AX.activationPoint={187.5, 406}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 812}}; opaque; alpha=1>
      |  |  |  |  |--<RCTView:0x7f8bc2525ca0; AX=N; AX.id='findme'; AX.frame={{0, 0}, {100, 100}}; AX.activationPoint={50, 50}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {100, 100}}; opaque; alpha=1>
      |  |  |  |  |  |--<RCTView:0x7f8bc242ddc0; AX=N; AX.frame={{0, 0}, {26, 100}}; AX.activationPoint={13, 50}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {26, 100}}; opaque; alpha=1>]

      14 |   });
      15 |
    > 16 |   fit('should find element', async () => {
         |   ^
      17 |     await expect(element(by.id("findme"))).toBeVisible();
      18 |   });
      19 |

      at Env.fit (../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.fit (firstTest.spec.js:16:3)
      at Object.describe (firstTest.spec.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 skipped, 3 total
Snapshots:   0 total
Time:        9.808s, estimated 10s
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
detox[15760] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd
detox[15760] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=63378d22-6054-f2b3-d7fa-c29c11ab76fd
detox[15758] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' "e2e"
```

**Comment by LeoNatan** [comment] 2019-04-18 21:24
That's a strange issue. I will need to look at how the native hierarchy looks like to see what is going on. Thanks for the examples.

**Comment by defualt** [comment] 2019-04-19 16:43
Probably related so including here instead of a separate issue:

Here are some more examples, but these involve a child element exceeding the bounds of a parent, and the excess being hidden by either scroll or overflow-hidden.

These should all pass.

## parent height 74, child height 100, overflow visible, PASSES

```
<View style={{height:74,overflow:'hidden'}}>
  <View style={{height: 100}} testID="findme"/>
</View>
```

## parent height 74, child height 100, overflow hidden, FAILS

*overflow hidden differs from previous*

```
<View style={{height:74,overflow:'hidden'}}>
  <View style={{height: 100}} testID="findme"/>
</View>
```

## parent height 75, child height 100, overflow hidden, PASSES

*parent height 75 differs from previous*

```
<View style={{height:75,overflow:'hidden'}}>
  <View style={{height: 100}} testID="findme"/>
</View>
```

## parent height 75, child height 100, ScrollView scenario, PASSES

*inner wrap a ScrollView in place of overflow hidden differs from previous*

```
<View style={{height:75}}>
  <ScrollView>
    <View style={{height: 100}} testID="findme"/>
  </ScrollView>
</View>
```

## parent height 74, child height 100, ScrollView scenario, FAILS

*parent height 74 differs from previous*

```
<View style={{height:74}}>
  <ScrollView>
    <View style={{height: 100}} testID="findme"/>
  </ScrollView>
</View>
```

**Comment by louy** [comment] 2019-08-12 10:16
Is there any workaround for this issue or any pointers as to why it's happening? We've started to face it now and it's pretty inconvenient

**Comment by LeoNatan** [comment] 2020-05-24 22:44
I've reimplemented the entire visibility testing for a future release. Since this is an older issue, I'll close it and will update once we release the new version. When that is out, please test and see if this reproduces. In the new implementation, visibility is tested in a similar way to how iOS calculates hit-testing (touches), so it should be a lot stable, hopefully.

**Closed by LeoNatan** 2020-05-24 22:44 UTC
Labels: type: triage/bug, z_platform: ios, 📌 pinned
