### ISSUE TITLE
scrollTo() edges on Flat List carries on scrolling when reaching the end

### ISSUE THREAD

**Issue by j320** [wix/Detox#2029] opened 2020-05-02 14:39 UTC
### Description
When using scrollTo('right') or left on FlatList, Detox carries on scrolling after reaching the end of the list.

#### Reproduction
1. Have an app with a FlatList containing several elements horizontally
2. Add a testID to the ScrollView of the FlatList
3. Use scrollTo() (right or left, where the list carries on)

#### Expected behavior
Detox ends the scrolling when it reaches the end of the list.

#### Environment (please complete the following information):
- Detox: 16.3.0
- React Native: 0.62.2
- Node: 14.0.0
- Device: iPhone 11
- Xcode: 11.4.1
- iOS: 13.4.1

**Comment by LeoNatan** [comment] 2020-05-03 08:45
Could you please create a small project that recreates this?

While we probably won't be able to fix this in the current Earl Grey implementation of scrolling, we are working on major rewrites that will be using a bespoke implementation, and I would like to under stand what the issue is exactly so we can get it right in that implementation. It could be that there is no way to know we've reached the end of the content size due to shenanigans in the FlatList implementation.

**Comment by j320** [comment] 2020-05-03 09:13
Sure, I'll get you one as soon as I can. Thanks.

**Comment by LeoNatan** [comment] 2020-05-03 09:17
Thank you!

**Comment by j320** [comment] 2020-05-03 12:41
Here: https://github.com/j320/detox_flatlistedges

**Comment by LeoNatan** [comment] 2020-05-03 13:28
Thank you! Please do not delete this repo.

**Comment by Kouznetsov** [comment] 2020-06-11 12:36
I seem to have the same issue with swipe(), the swipe just doesn't stop, so the Promise is never resolved.

**Comment by LeoNatan** [comment] 2020-06-25 19:40
Please try on latest Detox version and report back. Thanks

**Comment by j320** [comment] 2020-06-26 11:13
I've tested and test passes, however it doesn't scroll at all, this happens both on Android and iOS.

On iOS, if I expect an element out of bounds in the FlatList to exist, it passes, therefore it's in the iOS hierarchy at least. Although I guess we want same functionality on both platforms, perhaps it could try and scroll on both?

**Comment by LeoNatan** [comment] 2020-06-26 12:02
The issue here was infinite scroll. The Android exist is a separate issue.

**Comment by j320** [comment] 2020-06-26 12:17
So the current situation of no scrolling at all is the desired outcome?

**Comment by LeoNatan** [comment] 2020-06-26 19:00
Doesn’t sound right. I’ll look to reproduce with your repo.

**Comment by LeoNatan** [comment] 2020-11-03 17:26
Please try with the latest version of Detox and see if it reproduces. There were many recent changes made to scrolling.

**Comment by LeoNatan** [comment] 2020-11-15 09:47
I'll close this issue. If a similar issue persists, please open a new one. Thanks

**Closed by LeoNatan** 2020-11-15 09:47 UTC
Labels: type: accepted/bug, z_platform: ios, 📌 pinned
