### ISSUE TITLE
TypeError: Cannot read property 'identifier' of undefined

### ISSUE THREAD

**Issue by redbluenat** [wix/Detox#1565] opened 2019-07-30 11:40 UTC
**Description**
I have a problem from this lib during running detox tests, simulators for react native works okay. 

**Screenshots**
detox[17229] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 TypeError: Cannot read property 'identifier' of undefined
    at AppleSimUtils.create (/.../node_modules/detox/src/devices/ios/AppleSimUtils.js: 100:100)

**Environment**
 - macOS version: 10.14.5
 - Xcode version: 10.3

Before Xcode update I didn't have this issue

**Comment by LeoNatan** [comment] 2019-07-30 14:13
@redbluenat What version of applesimutils are you using?

**Comment by redbluenat** [comment] 2019-07-30 14:14
@LeoNatan applesimutils version 0.7.0

**Comment by LeoNatan** [comment] 2019-07-30 14:17
Very odd. I don't see a change in the output format from simctl, so applesimutils is exporting correctly.

**Comment by LeoNatan** [comment] 2019-07-30 14:18
Can you post your Detox config from package.json?

**Comment by redbluenat** [comment] 2019-07-30 15:09
"ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/app.app",
        "build": "xcodebuild -workspace ios/app.xcworkspace -scheme app -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone Xs"
      },

**Comment by KaushanF94** [comment] 2019-08-07 09:25
same issue

**Comment by ken0x0a** [comment] 2019-08-21 07:59
@LeoNatan hello!

I got similar error

`detox[13114] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR]`

but details are bit different.

As I got always **`by.id` is not a funciton**,
I did `console.log` and got followings
```js
import { by, element, expect } from "detox";
// ...
// in test case
console.log({ by, element, expect }); // => { by: {}, element: [Function], expect: [Function] }
```

detox@14.0.2
applesimutils version 0.7.1

**Comment by LeoNatan** [comment] 2019-08-21 08:03
@noomorph Any insights here? Thanks

**Comment by noomorph** [comment] 2019-08-21 08:17
Of course, the insight is that detox.init has not been called. Currently, by.id functions are platorm-specific, and initiated inside detox.init. If it is important for you to have a very early access to them, post a feature request and we'll see what we can do.

**Comment by LeoNatan** [comment] 2019-08-21 08:21
@noomorph Thanks! Could it also be that the `init()` somehow failed and that is causing this? Do you know what `detox[13114] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR]` is?

**Comment by noomorph** [comment] 2019-08-21 08:24
Exactly, thats it. Init has failed

**Comment by ken0x0a** [comment] 2019-08-21 15:32
It turns out my issue is related to 
- #1422 
- #917

**Comment by redbluenat** [comment] 2019-08-23 09:44
I resolved this issue by updating Detox and 

```
gem install xcode-install
xcversion simulators --install='iOS 12.4'
```

and add to configuration 

```
 "name": "iPhone X, iOS 12.4"
```

**Comment by WilGatlin** [comment] 2019-09-03 19:14
I am still having this issue but only with threading. Particularly we are using `--workers=3`, though the # of workers as long as its over 1 doesnt matter and will throw the error. 

This is using jest and latest v of detox.

**Comment by WilGatlin** [comment] 2019-09-04 14:00
Seems to be linked to this issue? https://github.com/wix/Detox/issues/1395

**Comment by WilGatlin** [comment] 2019-09-04 18:57
Resolved by cleaning out all previous xcode and applesimutils. Reinstalling both with latest.

**Comment by LeoNatan** [comment] 2019-10-07 07:21
We might have reproduced this issue locally.

**Closed** 2019-10-10 07:56 UTC
Labels: type: accepted/bug, z_platform: ios
