### ISSUE TITLE
iOS keyWindow.rootViewController would be null when app is driven by Detox.

### ISSUE THREAD

**Issue by Ponyets** [wix/Detox#1230] opened 2019-03-26 07:15 UTC
**Describe the bug**
In some legacy iOS code, some developers use `[UIApplicaiton sharedApplication].keyWindow.rootViewController` as a convenient way to get a VC instance.
When the app is driven by Detox, this call would return null.

It's because Detox creates a DTXTouchVisualizerWindow without any ViewController, then set it's windowLevel to a very high value and make it the keyWindow.

Surely, `[UIApplicaiton sharedApplication].keyWindow.rootViewController` isn't good way to access a VC instance, but it's widely used.

**To Reproduce**
1. Write a code block in an iOS app, like the callback of a button click, which tries to get a VC instance by calling `[UIApplicaiton sharedApplication].keyWindow.rootViewController`  and use the VC instance to present another ViewController.
2. Build and run the app in simulator, then manually test the functionality of the above code block. The new ViewController would be presented. Everything is fine.
3. Write a test case for this code block, and run it with Detox.
4. The code block doesn't work properly, the new ViewController wouldn't be presented.

**Expected behavior**
The functionality keeps exactly the same as it's in manual test.

**Environment (please complete the following information):**
 - Detox: 11.0.2
 - React Native: 0.55.4
 - Node: 11.9.0
 - Device: iOS Simulator & iPhone Xs Max
 - Xcode: 10.1
 - iOS: 12.1
 - macOS: 10.14.3

**Comment by LeoNatan** [comment] 2019-03-26 09:10
Hello,

I am looking at the code, and touch indicator window is not made key at any point. 
Perhaps the legacy applications forgot to call `makeKeyAndVisible` or `makeKeyWindow`?
From what you describe, the issue can occur if any system window (of which there can be any number of them—such as the dictionary when you tap "Look Up").

I am not sure about your PR either, because it can be often incorrect when several `UIWindow` instances exist (more complex apps). I don't think it's the right move to break Detox for complex apps in favor of apps that cannot be bothered to use iOS APIs correctly.

**Comment by LeoNatan** [comment] 2019-03-27 16:42
I am playing around, trying to reproduce a case where the touch indicator window is key, and cannot. In some cases, it seems `[[UIApplication sharedApplication] keyWindow]` returns `nil`, which makes sense.

**Comment by Ponyets** [comment] 2019-03-29 02:49
Hello Leo,

Thanks.

I just double checked our code, and confirmed that we did call `makeKeyAndVisible` of the AppDelegate's window in the `didFinishLaunchingWithOptions` method. 

As you saw in my PR, though it's not the right solution, it did prove the touch indicator window somehow became the key window.

I have updated the PR as your suggestion. 

I will check the behavior of the touch indicator with a demo or the examples, will update the conclusion soon.

**Comment by LeoNatan** [comment] 2019-03-29 10:44
Great, thanks

**Comment by LeoNatan** [comment] 2019-03-29 10:45
Merged the PR. Thank you for checking and submitting.

**Closed by LeoNatan** 2019-03-29 10:45 UTC
Labels: platform: ios, type: accepted/bug

**Comment by Ponyets** [comment] 2019-03-31 07:00
Hello Leo,

I couldn't reproduce this issue in a demo project. This seems only appear in some special circumstances which I can't tell now.

I will close this issue then. Thanks for your help.

**Comment by LeoNatan** [comment] 2019-03-31 08:18
Just to make sure, the fix in your PR solved your project’s issue, right?
