### ISSUE TITLE
Multiapps config: undescriptive error in case of missing device config

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2757] opened 2021-04-22 15:05 UTC
## Description
In a use case where a configuration is defined with an app in the new format (i.e. with an `app` or even `apps` field), but a `device` is not specified (rather, an explicit `type` is used - e.g. `"type": "ios.simulator"`), the resulted error is this:

```
Missing "binaryPath" property in the app config.
```

Which isn't helpful. Need to consider this use case in the config validation, and output a clearer error.

**Comment by noomorph** [comment] 2021-05-06 08:34
Yeah, will do. Thanks.

**Comment by noomorph** [comment] 2021-05-25 11:52
@d4vidi, could you provide an exact Detox config where this issue reproduces?
Unfortunately, I am not able to reproduce this according to the description.
Let's make bug reports less vague, ok? What would it have costed for you to paste an excerpt of Detox config back then, right? 😊

**Comment by d4vidi** [comment] 2021-05-25 12:29
Hmm. IMO, the description is pretty clear 😄 
You can try to edit one of Detox' self configs - have the device removed, and instead add a `type` field. Does it not reproduce this way? 😢

**Comment by noomorph** [comment] 2021-05-31 13:52
Resolved in [18.16.0](https://github.com/wix/Detox/releases/tag/18.16.0).

**Closed by noomorph** 2021-05-31 13:52 UTC
Labels: type: accepted/bug, z_domain: ux
