### ISSUE TITLE
Detox crash when typing text: `Signal 4 was raised`

### ISSUE THREAD

**Issue by jd20** [wix/Detox#2473] opened 2020-11-19 03:07 UTC
### Description
Detox is crashing about 20% of the time for me, when running a specific test case that logs into my app. The crash occurs when calling `typeText()` for entering the password, but also if I use `replaceText()` as well. The password is entered successfully, but Detox crashes maybe a second later, while the app is updating. I've tried removing various parts of the login code, to narrow down what causes the crash, but there does not appear to be any specific piece of code which triggers it to crash.

First noticed the issue with 17.10.3, and it persists even after upgrading to 17.12.0.

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Have been unsuccessful in isolating down to a reproducible test case that I can share, if I comment out all of the login code that executes after the `typeText()` call, Detox stops crashing. But if I try to narrow down which piece of code introduces the crash, I've had no luck doing so.

#### Expected behavior
Would expect Detox not to crash when calling `typeText()`.

#### Environment (please complete the following information):
 - Detox: 17.12.0
 - React Native: 0.63.3
 - Node: 13.14.0
 - Device: iPhone 8 Plus
 - Xcode: 12.1
 - iOS: 14.1
 - macOS: 10.15.7

#### Device and verbose Detox logs
- [X] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

Crash from the Detox logs:

```
detox[89117] INFO:  at test/e2e/login.test.ts:76:21 
 [LoginStore] Typing password...
detox[89117] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"type":"action","action":"typeText","params":["6789"],"predi
cate":{"type":"id","value":"recovery.password"}},"messageId":11}
detox[89117] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=66448d56-34b5-4f7d-dbee-9ab9b268d1d9)
detox[89117] TRACE: [DetoxServer.js/MESSAGE] role=testee action=AppWillTerminateWithError (sessionId=66448d56-34b5-4f7d-dbee-9ab9b268d1d9)
detox[89117] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"AppWillTerminateWithError","params":{"threadNumber":1,"errorDetails":"Signa
l 4 was raised\n(\n\t0   Detox                               0x00000001091910e1 __DTXHandleSignal + 59\n\t1   libsystem_platform.dylib        
    0x00007fff5df9c5fd _sigtramp + 29\n\t2   ???                                 0x0000000000000200 0x0 + 512\n\t3   EarlGrey                            0x000000010db1cd42 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 50\n\t4   libdispatch.dylib                   0x00007fff2010535b _dispatch_call_block_and_release + 12\n\t5   libdispatch.dylib                   0x00007fff20106534 _dispatch_client_callout + 8\n\t6   libdispatch.dylib                   0x00007fff20113011 _dispatch_main_queue_callback_4CF + 1045\n\t7   CoreFoundation                      0x00007fff203a8276 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9\n\t8   CoreFoundation                      0x00007fff203a2b06 __CFRunLoopRun + 2685\n\t9   CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567\n\t10  EarlGrey                            0x000000010db3d1cb -[GREYRunLoopSpinner grey_drainRunLoopInActiveModeAndCheckCondition:forTime:] + 651\n\t11  EarlGrey                            0x000000010db3cafd -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 637\n\t12  EarlGrey                            0x000000010db8cd78 -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1384\n\t13  EarlGrey                            0x000000010db8c7c7 -[GREYUIThreadExecutor executeSync:error:] + 311\n\t14  Detox                               0x000000010917865e __45-[EarlGreyImpl(Detox) detox_safeExecuteSync:]_block_invoke + 141\n\t15  CoreFoundation                      0x00007fff203a85db __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12\n\t16  CoreFoundation                      0x00007fff203a79ef __CFRunLoopDoBlocks + 434\n\t17  CoreFoundation                      0x00007fff203a2a6d __CFRunLoopRun + 2532\n\t18  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567\n\t19  EarlGrey                            0x000000010db3ddcd -[GREYRunLoopSpinner grey_checkConditionInActiveMode:] + 381\n\t20  EarlGrey                            0x000000010db3ca32 -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 434\n\t21  EarlGrey                            0x000000010db8cd78 -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1384\n\t22  EarlGrey                            0x000000010db8c7c7 -[GREYUIThreadExecutor executeSync:error:] + 311\n\t23  Detox                               0x000000010917865e __45-[EarlGreyImpl(Detox) detox_safeExecuteSync:]_block_invoke + 141\n\t24  CoreFoundation                      0x00007fff203a85db __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12\n\t25  CoreFoundation                      0x00007fff203a79ef __CFRunLoopDoBlocks + 434\n\t26  CoreFoundation                      0x00007fff203a2a6d __CFRunLoopRun + 2532\n\t27  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567\n\t28  GraphicsServices                    0x00007fff2b793db3 GSEventRunModal + 139\n\t29  UIKitCore                           0x00007fff2466d40f -[UIApplication _run] + 912\n\t30  Detox                               0x00000001091899bb __detox_UIApplication_run + 365\n\t31  UIKitCore                           0x00007fff24672320 UIApplicationMain + 101\n\t32  Beta App                            0x0000000108ac491b main + 75\n\t33  libdyld.dylib                       0x00007fff20257409 start + 1\n\t34  ???                                 0x000000000000000a 0x0 + 10\n)","queueName":"com.apple.main-thread"},"messageId":-10000}
 
detox[89117] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestFnFailure({
  error: Error: Signal 4 was raised
  (
        0   Detox                               0x00000001091910e1 __DTXHandleSignal + 59
        1   libsystem_platform.dylib            0x00007fff5df9c5fd _sigtramp + 29
        2   ???                                 0x0000000000000200 0x0 + 512
        3   EarlGrey                            0x000000010db1cd42 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 50
        4   libdispatch.dylib                   0x00007fff2010535b _dispatch_call_block_and_release + 12
        5   libdispatch.dylib                   0x00007fff20106534 _dispatch_client_callout + 8
        6   libdispatch.dylib                   0x00007fff20113011 _dispatch_main_queue_callback_4CF + 1045
        7   CoreFoundation                      0x00007fff203a8276 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        8   CoreFoundation                      0x00007fff203a2b06 __CFRunLoopRun + 2685
        9   CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
        10  EarlGrey                            0x000000010db3d1cb -[GREYRunLoopSpinner grey_drainRunLoopInActiveModeAndCheckCondition:forTime:] + 651
        11  EarlGrey                            0x000000010db3cafd -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 637
        12  EarlGrey                            0x000000010db8cd78 -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1384
        13  EarlGrey                            0x000000010db8c7c7 -[GREYUIThreadExecutor executeSync:error:] + 311
        14  Detox                               0x000000010917865e __45-[EarlGreyImpl(Detox) detox_safeExecuteSync:]_block_invoke + 141
        15  CoreFoundation                      0x00007fff203a85db __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
        16  CoreFoundation                      0x00007fff203a79ef __CFRunLoopDoBlocks + 434
        17  CoreFoundation                      0x00007fff203a2a6d __CFRunLoopRun + 2532
        18  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
        19  EarlGrey                            0x000000010db3ddcd -[GREYRunLoopSpinner grey_checkConditionInActiveMode:] + 381
        20  EarlGrey                            0x000000010db3ca32 -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 434
        21  EarlGrey                            0x000000010db8cd78 -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1384
        22  EarlGrey                            0x000000010db8c7c7 -[GREYUIThreadExecutor executeSync:error:] + 311
        23  Detox                               0x000000010917865e __45-[EarlGreyImpl(Detox) detox_safeExecuteSync:]_block_invoke + 141
        24  CoreFoundation                      0x00007fff203a85db __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
        25  CoreFoundation                      0x00007fff203a79ef __CFRunLoopDoBlocks + 434
        26  CoreFoundation                      0x00007fff203a2a6d __CFRunLoopRun + 2532
        27  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
        28  GraphicsServices                    0x00007fff2b793db3 GSEventRunModal + 139
        29  UIKitCore                           0x00007fff2466d40f -[UIApplication _run] + 912
        30  Detox                               0x00000001091899bb __detox_UIApplication_run + 365
        31  UIKitCore                           0x00007fff24672320 UIApplicationMain + 101
        32  Beta App                            0x0000000108ac491b main + 75
        33  libdyld.dylib                       0x00007fff20257409 start + 1
        34  ???                                 0x000000000000000a 0x0 + 10
  )
      at call (/Users/jd20/app/test/e2e/login.test.ts:53:52)
      at tryCatch (/Users/jd20/app/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator._invoke (/Users/jd20/app/node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.call (/Users/jd20/app/node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (/Users/jd20/app/node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (/Users/jd20/app/node_modules/regenerator-runtime/runtime.js:135:20)
      at fn (/Users/jd20/app/node_modules/regenerator-runtime/runtime.js:145:13)
      at tryCallOne (/Users/jd20/app/node_modules/promise/lib/core.js:37:12)
      at call (/Users/jd20/app/node_modules/promise/lib/core.js:123:15)
      at flush (/Users/jd20/app/node_modules/asap/raw.js:50:29)
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
})
```

The device logs (with `-detoxPrintBusyIdleResources YES`) are in the attached ZIP, the first part is cut off because it was so long. I've scrubbed both files of some logs and HTTP requests specific to our app, I don't think any of it would be relevant to the crash though.

[logs.zip](https://github.com/wix/Detox/files/5564085/logs.zip)

**Comment by LeoNatan** [comment] 2020-11-19 08:43
Hmmm

In the stack trace, I don’t see anything related to typing that is the cause. 

You mentioned that you disable login code, it stops crashing. Could you please provide more information? Do you mean code in your app, or code in you test? 

Thanks

**Comment by jd20** [comment] 2020-11-19 19:47
Meant login code in our app. The detox test is typing in a 4-digit code in a TextInput, and then it auto-submits and logs the user in. If I comment out all login code that gets triggered by the auto-submit, I cannot reproduce the crash. I tried re-enabling pieces of the code bit by bit, but there doesn't seem to be anything specific that triggers the crash (just once I re-enable enough stuff, it will start crashing again, so I suspect there's something timing related).

The line in the detox test that's crashing looks like:

```javascript
        console.log(`[LoginStore] Typing password...`)
        await element(by.id('recovery.password')).typeText(testPassword())
```

**Comment by LeoNatan** [comment] 2020-11-19 19:59
I don’t think it’s detox that is crashing, but your code. Try putting breakpoints and following your code. Also try `replaceText()` and see if that one doesn’t crash. If it works, maybe your code is crashing because `typeText()` is typing each character quickly and your code JS some bad race condition. 

At this point, I don’t think this is related to Detox. Let me know if you find more info that makes you think it’s Detox. Closing for now. Thanks

**Closed by LeoNatan** 2020-11-19 19:59 UTC
Labels: type: triage/bug, z_platform: ios

**Comment by jd20** [comment] 2020-11-19 21:57
Hi, I did attempt changing from `typeText()` to `replaceText()`, same crash.

From the call stack, any insights as to what the crash might be triggered by? Would help if I had some idea what to pay more attention to, while I'm trying to isolate a repro case.

**Comment by LeoNatan** [comment] 2020-11-19 22:37
I don't really see anything that looks suspicious. You can see "Detox" and "Earl Grey" in there, but those are standard things that Detox injects.

Let's try the following:
https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md

Follow the guide, enable exception breakpoints, reproduce the issue and post here what you see in Xcode.

Thanks

**Comment by jd20** [comment] 2020-11-20 01:04
Thanks, I was able to run it from Xcode following the guide above, although the issue no longer reproduces when run that way. It makes me wonder if part of the issue is how we launch the app each time (currently we set `"launchApp": false` in `package.json`, and call it manually in `beforeEach()` as `await device.launchApp({ delete: true })`).

Going to see if I can reliably reproduce the crash without manually calling `launchApp()`, will report back what I find.

**Comment by jd20** [comment] 2020-12-12 04:18
Hi @LeoNatan, I finally was able to create a simple repro case of this issue, and narrow down the piece of code that triggers the crash. It's caused when Detox is synchronizing, and `Instabug.identifyUser()` is called.

You should be able to repro with the following steps now:

```
git clone https://github.com/jd20/DetoxCrash.git
cd DetoxCrash
yarn install
yarn ios:clean
yarn detox build
yarn detox test
```

I sometimes have to run the `yarn detox test` 2 or 3 times to see the crash, but usually it happens with just one try. Does it make sense to reopen this issue, if we have a working repro case?

**Comment by davidquo** [comment] 2021-11-04 18:42
jd20 seems to be onto something.  Solution of not running Instabug during testing should work.
