### ISSUE TITLE
Can't use .scroll() and .swipe() for MapView from react-native-maps

### ISSUE THREAD

**Issue by mhyousefi** [wix/Detox#250] opened 2017-08-27 06:28 UTC
#### I have a `MapView` from `react-native-maps` in my app somewhere and would like to move the chosen location using the `scroll` or the `swipe` action methods. 

It works (and zooms a bit) when I try:
```
await expect(element(by.id(<map test ID>)).toBeVisible()
await element(by.id(<map test ID>)).multiTap(2)
```

But when trying this:
```
await expect(element(by.id(<map test ID>)).toBeVisible()
await element(by.id(<map test ID>)).scroll(50, 'down')
```
or this
```
await expect(element(by.id(<map test ID>)).toBeVisible()
await element(by.id(<map test ID>)).swipe('down', 'slow')
```

I get the following error:
```
Error: Cannot find UI element.
Exception with Action: {
  "Action Name" : "Scroll Down for 100",
  "Element Matcher" : "(((((kindOfClass('UIScrollView') || kindOfClass('UIWebView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('SetLocationView-MapView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('SetLocationView-MapView')))))) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((((kindOfClass('UIScrollView') || kindOfClass('UIWebView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('SetLocationView-MapView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('SetLocationView-MapView')))))) && kindOfClass('RCTScrollView'))))))",
  "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
}

Error Trace: [
  {
    "Description" : "Interaction cannot continue because the desired element was not found.",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "0",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
    "Line" : "124"
  }
]
```

**Comment by isnifer** [comment] 2017-08-27 07:30
I had the same result with appium. Sadly, but react-native-maps inaccessible for now

**Comment by sraikimaxime** [comment] 2018-12-03 12:11
Hi there @LeoNatan, first of all thanks for the amazing library, I'd love to start improving the detox experience on react native maps as I'd want to use it on the project I'm currently working on, is there any other work ongoing on this topic ? Thank you for your time !

**Comment by LeoNatan** [comment] 2018-12-03 12:13
Hello

Thank you for your desire to contribute! There is no other effort in this area that I am aware of.

**Comment by sraikimaxime** [comment] 2018-12-03 12:14
Sweet, do you have any advice before I start digging ? :)

**Comment by LeoNatan** [comment] 2018-12-03 12:16
I suggest looking first at how Earl Grey on iOS and Espresso on Android handle map scrolling. If it works but is broken in Detox, I suggest looking at which view Detox attempts to scroll.
If it doesn't work, I would either suggest creating an enhancement with Earl Grey or doing it directly in Detox. Let's discuss further once we have deeper understanding of Earl Grey.

**Comment by sraikimaxime** [comment] 2018-12-30 19:00
Hey @LeoNatan, thank you for your help, sorry I have not been really focus these days with the end of year celebrations :).

So I've been looking at Earl Grey for now and I have understood that they use swipe and pinch actions to interact with maps. Also I've started the implementation of EARLGrey actions to allow us to pinch and did a first test with a map having the expected behavior. I opened a WIP PR so that you could challenge the implementation as soon as possible but will now add the actions to the action generator and make sure the lib still passes the tests.
Here is the [PR](https://github.com/wix/Detox/pull/1104) and the [associated issue](https://github.com/wix/Detox/issues/1105), I was not sure if I was supposed to open a new one or to refer this one.

Thank you for your time and help.

**Comment by LeoNatan** [comment] 2019-04-15 22:28
Since this has been resolved in PRs, I am closing the issue. Thanks

**Closed by LeoNatan** 2019-04-15 22:28 UTC
Labels: type: accepted/bug, user: looking for contributors
