### ISSUE TITLE
Not working with React 16 // RN 0.48.4

### ISSUE THREAD

**Issue by rjanjua** [wix/detox#312] opened 2017-10-04 14:11 UTC
#### Description

We upgraded our app to React 16.0.0 with React Native 0.48.4 and all of our tests timed out. They are very simple tests, they just check that some text exists on the page

```
      await expect(element(by.text(`Some text`))).toBeVisible();
```
There is no other interaction.

#### Node, Device, Xcode and macOS Versions

* Node: v8.1.2
* Device: iPhone 7 Simulator, iOS 10.3
* Xcode: 8.3.2
* macOS: Sierra

**Comment by xcarpentier** [comment] 2017-10-04 14:40
Maybe the same as: #279

**Comment by rjanjua** [comment] 2017-10-04 14:44
looks very similar - thanks @xcarpentier

**Comment by LeoNatan** [comment] 2017-10-06 15:39
The issue is tracked elsewhere. Closing

**Closed by LeoNatan** 2017-10-06 15:39 UTC
