### ISSUE TITLE
Detox fails launching with error [NSURL initFileURLWithPath:] in applesimutils

### ISSUE THREAD

**Issue by shamilovtim** [wix/Detox#3155] opened 2021-12-29 07:19 UTC
### Description
Occasionally when starting Detox + iOS emulator on CI it will flake and not run with the following error message. There are a number of people who have reported this problem in the past and some proposed solutions from random contributors but from what I can tell nothing has been applied to the repo yet.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

1. Launch detox with `yarn detox test -c ci.ios.release`
2. Receive error `[NSURL initFileURLWithPath:]: nil string parameter` . Full error down below

#### Expected behavior

Expect no flakes when launching Detox or iOS 

#### Environment
Circle CI 
macOS Node Orb 4.7.0

 - Detox: 19.4.1
 - React Native: 0.65.2
 - Node: 14.17.3
 - Device: 13 Pro Max Simulator
 - Xcode: 13.2.1
 - iOS: 15.2
 - macOS: 11.6
 - Test-runner (select one): `jest-circus` 
#### If you are experiencing a timeout in your test

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

```
detox[7706] INFO:  [AppleSimUtils.js] com.shipt.groceries-staging launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 760EAD26-C92A-42B7-9252-DF691A8E8FDF log stream --level debug --style compact --predicate 'process == "Shipt"'
detox[7706] INFO:  Restart user membership is assigned to 760EAD26-C92A-42B7-9252-DF691A8E8FDF (iPhone 13 Pro Max)
detox[7706] INFO:  Restart user membership: should signup and add payment method
detox[7706] ERROR: [EXEC_FAIL, #33] "applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO" failed with error = ChildProcessError: Command failed: applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO
*** -[NSURL initFileURLWithPath:]: nil string parameter. See “applesimutils --help” for usage.
 `applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO` (exited with error code 255) (code=255), stdout and stderr:

detox[7706] ERROR: [EXEC_FAIL, #33] 
detox[7706] ERROR: [EXEC_FAIL, #33] *** -[NSURL initFileURLWithPath:]: nil string parameter. See “applesimutils --help” for usage.
```

**Comment by asafkorem** [comment] 2022-01-02 12:58
Thanks for the report @shamilovtim, I will look into it.
Does it happens for you only when you set the location permissions through the `launchApp()`?

**Comment by asafkorem** [comment] 2022-01-02 13:15
@shamilovtim this comment seems to be relevant for this issue as well: https://github.com/wix/Detox/issues/3154#issuecomment-1003714203.

**Comment by shamilovtim** [comment] 2022-01-14 00:13
@asafkorem Do you have any advice for how we could go about fixing this issue? Similar to the problems signal 11 was causing, this is flaking our whole test suite.

**Comment by asafkorem** [comment] 2022-01-16 09:32
Hi @shamilovtim, I will try to reproduce this now.

**Comment by asafkorem** [comment] 2022-01-16 09:37
@shamilovtim it's a bit of a problem to reproduce this by myself because we are not using CircleCI. Anyway I'll try to investigate the relevant code and to see if some problem emerge

**Comment by shamilovtim** [comment] 2022-01-16 10:44
Happy to help in any way I can. Maybe I can get a public sandbox for circle and run a development version of applesimutils with extra debug logging

**Comment by asafkorem** [comment] 2022-01-17 08:24
@shamilovtim can you please answer https://github.com/wix/Detox/issues/3155#issuecomment-1003712161?
If you remove the setLocation from the launchApp method, is it still happening?

**Comment by asafkorem** [comment] 2022-01-17 08:56
@shamilovtim I have a strong feeling that this issue and https://github.com/wix/Detox/issues/3154 are very connected.
We can focus on resolving #3154 and then get back to this one.

**Comment by shamilovtim** [comment] 2022-01-26 15:36
It looks like using launchApp without any permissions fixes the issue

**Closed** 2022-01-26 15:37 UTC
Labels: z_platform: ios, type: triage/bug
