### ISSUE TITLE
Detox core should not read --configuration name from argv directly

### ISSUE THREAD

**Issue by MoOx** [wix/detox#338] opened 2017-10-13 10:09 UTC
I am using Jest just followed [Jest guide](https://github.com/wix/detox/blob/0acf4b89a895e8e7f9f2a5b4e48537eed3a73cba/docs/Guide.Jest.md).
The problem is: jest cli validate the argv arguments.
So you cannot just throw --configuration here.
The thing is: detox [rely on argv to read this option](https://github.com/wix/detox/blob/cd4d8a1b8accf63f4abdb8bfc4a644d05a8222e1/detox/src/Detox.js#L118) so we cannot configure this via node API.
Are you open to a change to make configuration name an option for the node API too? Btw, argv thing should be on CLI, no in the core.

**Comment by rotemmiz** [comment] 2017-10-13 11:18
https://github.com/wix/detox/pull/335

**Comment by MoOx** [comment] 2017-10-13 12:18
This might help indeed, but I guess I will leave this issue open as it can happen for other runner until those are implemented. Will rename issue accordingly.

**Comment by Kureev** [comment] 2017-10-13 12:42
Hi @MoOx! You can already check implementation in #335 😉

**Comment by MoOx** [comment] 2017-10-13 12:49
Yeah I saw this once, nice job :)

**Comment by Kureev** [comment] 2017-10-19 01:31
detox@5.9.0 has been released with #335 in it. Should be solved now, right? Can you please verify that the issue is gone now and if so, close the issue?

**Comment by rotemmiz** [comment] 2017-11-12 18:36
Closing this issue, Detox core now reads both argv and env vars (to support Jest)

**Closed by rotemmiz** 2017-11-12 18:36 UTC
