### ISSUE TITLE
[RN 72] iOS Simulator cannot terminate app 

### ISSUE THREAD

**Issue by TheChrisOneil** [wix/Detox#4148] opened 2023-07-28 20:36 UTC
### What happened?

Added Detox to an existing react native project.  It failed to complete the detox test command due

child-process:EXEC_FAIL "/usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):

 
After reading about others who had similar issues, I assumed it was my project configuration. 
So I then used the sample in React Native and confirmed the AwesomeProject successfully deployed on the simulator.  Then followed the instructions from the Detox site and successfully ran detox build;  However, it fails in the same way as my original project. 

MacBook Pro - M1 2020
macOS Ventura 13.4.1
Xcode 14.3.1

detox test -l verbose --cleanup  --configuration ios.sim.debug 

### What was the expected behaviour?

The iOS simulator would terminate the app

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.11.1
React Native version: 0.72.3
Has Fabric (React Native's new rendering system) enabled: (yes/no) No
Node version: v20.5.0
Device model: iPhone 14
iOS version: 
macOS version:  Ventura 13.4.1. (M1 2020)
Xcode version:   14.3.1
Test-runner (select one): jest / other. Jest

### Detox logs

<details><summary>Detox logs</summary>

```
(base) thechrisoneil@Chriss-MacBook-Pro AwesomeProject % detox test -l verbose --cleanup  --configuration ios.sim.debug
15:27:01.491 detox[13335] i ws-server Detox server listening on localhost:50627...
15:27:01.495 detox[13335] B lifecycle jest --config e2e/jest.config.js
watchman warning:  Recrawled this watch 3 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/thechrisoneil/software/react-native/AwesomeProject' ; watchman watch-project '/Users/thechrisoneil/software/react-native/AwesomeProject'`

Determining test suites to run...
15:27:02.348 detox[13336] i child-process:EXEC_CMD applesimutils --list --byType "iPhone 14"
15:27:02.585 detox[13336] i child-process:EXEC_CMD applesimutils --list --byId B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 --maxResults 1
15:27:02.806 detox[13336] i child-process:EXEC_CMD /usr/bin/xcrun simctl boot B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 
15:27:02.806 detox[13336] i child-process:EXEC_TRY Booting device B9AD5297-A76B-41D8-9C0F-435F87BBE3B3...
15:27:03.259 detox[13336] i child-process:EXEC_CMD /usr/bin/xcrun simctl bootstatus B9AD5297-A76B-41D8-9C0F-435F87BBE3B3
15:27:06.770 detox[13336] i child-process:EXEC_CMD open -a Simulator --args -CurrentDeviceUDID B9AD5297-A76B-41D8-9C0F-435F87BBE3B3
15:27:06.838 detox[13336] i child-process:EXEC_CMD /usr/bin/xcrun simctl io B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 screenshot "/dev/null"
15:27:07.412 detox[13336] i child-process:EXEC_CMD /usr/bin/xcrun simctl uninstall B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject
15:27:07.412 detox[13336] i child-process:EXEC_TRY Uninstalling org.reactjs.native.example.AwesomeProject...
15:27:08.154 detox[13336] i child-process:EXEC_SUCCESS org.reactjs.native.example.AwesomeProject uninstalled
15:27:08.156 detox[13336] i child-process:EXEC_CMD /usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject
15:27:08.156 detox[13336] i child-process:EXEC_TRY Terminating org.reactjs.native.example.AwesomeProject...
15:27:09.600 detox[13336] i child-process:EXEC_TRY Terminating org.reactjs.native.example.AwesomeProject...
15:27:09.878 detox[13336] i child-process:EXEC_FAIL "/usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The request to terminate "org.reactjs.native.example.AwesomeProject" failed. found nothing to terminate
	found nothing to terminate
 `/usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject` (exited with error code 3) (code=3), stdout and stderr:

15:27:09.878 detox[13336] i child-process:EXEC_FAIL 
15:27:09.878 detox[13336] i child-process:EXEC_FAIL An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The request to terminate "org.reactjs.native.example.AwesomeProject" failed. found nothing to terminate
	found nothing to terminate

15:27:09.883 detox[13335] E ws-server connection :50627<->:50628
15:27:09.883 detox[13336] i child-process:EXEC_CMD /usr/bin/xcrun simctl shutdown B9AD5297-A76B-41D8-9C0F-435F87BBE3B3
15:27:09.883 detox[13336] i child-process:EXEC_TRY Shutting down B9AD5297-A76B-41D8-9C0F-435F87BBE3B3...
15:27:13.266 detox[13336] i child-process:EXEC_SUCCESS B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 shut down
 FAIL  e2e/starter.test.js
  ● Test suite failed to run

    ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
    Simulator device returned an error for the requested operation.
    found nothing to terminate
    Underlying error (domain=NSPOSIXErrorDomain, code=3):
    	The request to terminate "org.reactjs.native.example.AwesomeProject" failed. found nothing to terminate
    	found nothing to terminate
     `/usr/bin/xcrun simctl terminate B9AD5297-A76B-41D8-9C0F-435F87BBE3B3 org.reactjs.native.example.AwesomeProject` (exited with error code 3)

      at callback (node_modules/child-process-promise/lib/index.js:33:27)

15:27:13.385 detox[13335] E lifecycle Command failed with exit code = 1:
jest --config e2e/jest.config.js
15:27:13.386 detox[13335] i ws-server Detox server has been closed gracefully

```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by brettscott4** [comment] 2023-08-02 03:07
I am also experiencing this issue after upgrading react native to 0.72.3

**Comment by TheMakerOleguch** [comment] 2023-08-09 12:03
The same issue for RN 0.72.x
1. Old architecture
2. JSC engine
3. `"detox": "^20.11.2"`

`2023-08-08T22:24:50.8522480Z $ /Users/runner/work/node_modules/.bin/detox test -c ios.sim.release --cleanup --noStackTrace --detectOpenHandles --forceExit -l verbose --maxWorkers 1 --retries 1
2023-08-08T22:24:51.8858840Z 22:24:51.876 detox[31494] i ws-server Detox server listening on localhost:49302...
2023-08-08T22:24:51.9092590Z 22:24:51.908 detox[31494] B lifecycle jest --config detox.config.js --noStackTrace --detectOpenHandles --forceExit --maxWorkers 1
2023-08-08T22:24:55.4135880Z 22:24:55.413 detox[31494] B ws-server connection :49302<->:49303
2023-08-08T22:24:55.9851270Z 22:24:55.983 detox[31496] i child-process:EXEC_CMD applesimutils --list --byOS 16.4 --byType "iPhone 14"
2023-08-08T22:24:58.4659620Z 22:24:58.465 detox[31496] i child-process:EXEC_CMD applesimutils --list --byId E7678A35-F784-403F-ABF5-827436E79FCD --maxResults 1
2023-08-08T22:24:59.2978250Z 22:24:59.297 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl boot E7678A35-F784-403F-ABF5-827436E79FCD 
2023-08-08T22:24:59.2987550Z 22:24:59.298 detox[31496] i child-process:EXEC_TRY Booting device E7678A35-F784-403F-ABF5-827436E79FCD...
2023-08-08T22:25:01.8854810Z 22:25:01.885 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl bootstatus E7678A35-F784-403F-ABF5-827436E79FCD
2023-08-08T22:27:44.1819790Z 22:27:44.109 detox[31496] i child-process:EXEC_CMD open -a Simulator --args -CurrentDeviceUDID E7678A35-F784-403F-ABF5-827436E79FCD
2023-08-08T22:27:50.8327370Z 22:27:50.785 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl io E7678A35-F784-403F-ABF5-827436E79FCD screenshot "/dev/null"
2023-08-08T22:28:01.7893540Z 22:28:01.788 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl uninstall E7678A35-F784-403F-ABF5-827436E79FCD com.preply
2023-08-08T22:28:01.7921330Z 22:28:01.790 detox[31496] i child-process:EXEC_TRY Uninstalling com.preply...
2023-08-08T22:28:03.2143730Z 22:28:03.213 detox[31496] i child-process:EXEC_SUCCESS com.preply uninstalled
2023-08-08T22:28:03.2184800Z 22:28:03.217 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply
2023-08-08T22:28:03.2209710Z 22:28:03.218 detox[31496] i child-process:EXEC_TRY Terminating com.preply...
2023-08-08T22:28:05.1978220Z 22:28:05.197 detox[31496] i child-process:EXEC_TRY Terminating com.preply...
2023-08-08T22:28:05.9494000Z 22:28:05.948 detox[31496] i child-process:EXEC_FAIL "/usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply
2023-08-08T22:28:05.9510770Z An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:05.9512080Z Simulator device returned an error for the requested operation.
2023-08-08T22:28:05.9513350Z found nothing to terminate
2023-08-08T22:28:05.9514290Z Underlying error (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:05.9878790Z 	The operation couldn’t be completed. found nothing to terminate
2023-08-08T22:28:05.9880360Z 	found nothing to terminate
2023-08-08T22:28:05.9907910Z  `/usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply` (exited with error code 3) (code=3), stdout and stderr:
2023-08-08T22:28:05.9909060Z 
2023-08-08T22:28:05.9911800Z 22:28:05.949 detox[31496] i child-process:EXEC_FAIL 
2023-08-08T22:28:05.9914320Z 22:28:05.950 detox[31496] i child-process:EXEC_FAIL An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:05.9915430Z Simulator device returned an error for the requested operation.
2023-08-08T22:28:05.9916260Z found nothing to terminate
2023-08-08T22:28:05.9918260Z Underlying error (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:05.9944200Z 	The operation couldn’t be completed. found nothing to terminate
2023-08-08T22:28:05.9945840Z 	found nothing to terminate
2023-08-08T22:28:05.9946640Z 
2023-08-08T22:28:05.9952250Z 22:28:05.951 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl install E7678A35-F784-403F-ABF5-827436E79FCD "/Users/runner/work/os/build/Build/Products/Release-iphonesimulator/Preply.app"
2023-08-08T22:28:05.9961900Z 22:28:05.952 detox[31496] i child-process:EXEC_TRY Installing /Users/runner/work/apollo-mobile/apollo-mobile/ios/build/Build/Products/Release-iphonesimulator/Preply.app...
2023-08-08T22:28:13.3428700Z 22:28:13.251 detox[31496] i child-process:EXEC_SUCCESS /Users/runner/work/ios/build/Build/Products/Release-iphonesimulator/Preply.app installed
2023-08-08T22:28:13.4556110Z 22:28:13.261 detox[31496] i child-process:EXEC_CMD /usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply
2023-08-08T22:28:13.4999280Z 22:28:13.262 detox[31496] i child-process:EXEC_TRY Terminating com.preply...
2023-08-08T22:28:16.0312440Z 22:28:16.030 detox[31496] i child-process:EXEC_TRY Terminating com.preply...
2023-08-08T22:28:17.1719280Z 22:28:17.169 detox[31496] i child-process:EXEC_FAIL "/usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply
2023-08-08T22:28:17.1723720Z An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:17.1725710Z Simulator device returned an error for the requested operation.
2023-08-08T22:28:17.1728070Z found nothing to terminate
2023-08-08T22:28:17.1731520Z Underlying error (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:17.1734380Z 	The operation couldn’t be completed. found nothing to terminate
2023-08-08T22:28:17.1737050Z 	found nothing to terminate
2023-08-08T22:28:17.1740040Z  `/usr/bin/xcrun simctl terminate E7678A35-F784-403F-ABF5-827436E79FCD com.preply` (exited with error code 3) (code=3), stdout and stderr:
2023-08-08T22:28:17.1741040Z 
2023-08-08T22:28:17.1747480Z 22:28:17.172 detox[31496] i child-process:EXEC_FAIL 
2023-08-08T22:28:17.1754980Z 22:28:17.173 detox[31496] i child-process:EXEC_FAIL An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:17.1761510Z Simulator device returned an error for the requested operation.
2023-08-08T22:28:17.1763140Z found nothing to terminate
2023-08-08T22:28:17.1765540Z Underlying error (domain=NSPOSIXErrorDomain, code=3):
2023-08-08T22:28:17.1767520Z 	The operation couldn’t be completed. found nothing to terminate
2023-08-08T22:28:17.1769240Z 	found nothing to terminate`

**Comment by Yassir4** [comment] 2023-08-09 17:17
@TheMakerOleguch I faced the same issue in CI, but I somehow managed to workaround it by doubling the timeout time(in .detoxrc and jest.config).
as I think Detox keeps trying to install the app in Simulator until it succeeds.
Hope this will help someone

**Comment by TheMakerOleguch** [comment] 2023-08-11 09:30
@Yassir4 tried with 24000ms setup timeout with no luck

**Comment by asafkorem** [comment] 2023-08-27 13:30
It sounds like there's an issue with RN 72 and Detox. We don't officially support this version yet, but we will soon. We will take this issue into consideration when upgrading Detox to comply with RN 72.

**Comment by a-tokyo** [comment] 2023-09-12 13:49
A simple solution for CircleCI would be to add a `timeout` parameter to the step that runs `yarn detox test`. Not sure about GH actions but there must be an equivalent.

In our case, we added `timeout=300` which gracefully exits the job with exit code zero if no output was generated within 5 minutes. 

Of course this is a temporary solution until the final fix comes with RN 0.72 support

**Comment by only1chi** [comment] 2023-10-11 16:44
I'm seeing the same issue with RN 0.71.11 and Detox 19.5.7

**Comment by owens-ben** [comment] 2023-10-11 19:37
Some of my colleagues are seeing this on "react-native": "0.72.4", "detox": "20.9.1",

**Comment by PetroPavlenko** [comment] 2023-10-13 12:33
Hi all. 
With same codebase I'm able to reproduce this bug on machine with XCode 15. But it works well with previous XCode version. I've applied patch to `detox@19.13.0`. As a temporary solution to disable termination.
```
diff --git a/node_modules/detox/src/devices/runtime/drivers/ios/SimulatorDriver.js b/node_modules/detox/src/devices/runtime/drivers/ios/SimulatorDriver.js
index 878d483..1eacf07 100644
--- a/node_modules/detox/src/devices/runtime/drivers/ios/SimulatorDriver.js
+++ b/node_modules/detox/src/devices/runtime/drivers/ios/SimulatorDriver.js
@@ -107,9 +107,10 @@ class SimulatorDriver extends IosDriver {
 
   async terminate(bundleId) {
     const { udid } = this;
-    await this.emitter.emit('beforeTerminateApp', { deviceId: udid, bundleId });
-    await this._applesimutils.terminate(udid, bundleId);
-    await this.emitter.emit('terminateApp', { deviceId: udid, bundleId });
+    // await this.emitter.emit('beforeTerminateApp', { deviceId: udid, bundleId });
+    // await this._applesimutils.terminate(udid, bundleId);
+    // await this.emitter.emit('terminateApp', { deviceId: udid, bundleId });
   }
 
   async setBiometricEnrollment(yesOrNo) {
```

**Comment by PetroPavlenko** [comment] 2023-10-18 07:01
hi @kvramyasri7,
we use 
```
"react-native": "0.72.5"
"detox": "^19.13.0",
```
BTW in our version we added NO_FLIPPER config in `react-native.config.js` and installed pods without flipper.
Otherwise`detox build` is failing. Also IOS 17 version on simulator is 3 times slower in our CI machine. So we switched to IOS 16.4. 
p.s. this version of react-native has support of XCode 15.

**Comment by zhouzh1** [comment] 2023-10-30 01:36
Any official solutions to this issue? I'm using the RN 0.74.2 and Detox 20.9.1, after upgraded to Xcode15, this issue emerged, is there any avaliable version I can upgrade to?

**Comment by noomorph** [comment] 2023-10-31 09:55
We'll try to check soon if there are indeed some issues with Xcode 15.

**Comment by noomorph** [comment] 2023-10-31 13:29
Guys, we will only advance here if you create some exact reproduction repo. I understand you have an issue, but the conditions to reproduce this issue seem much more specific than originally described. There has to be something else in the equation.

**Comment by elliotmrodriguez** [comment] 2023-10-31 21:30
Hate to be a "me too" without anything substantive to add, but adding anyway just to reflect another user with the same problem. I can reproduce this reliably on my M1 Mac, v19.12.6 on 0.72.6.  If/when I find anything interesting I'll be sure to update.

**Comment by noomorph** [comment] 2023-11-01 00:34
Maybe M* platform issue then, hm?

**Comment by PetroPavlenko** [comment] 2023-11-01 07:40
after updating XCode to latest 15.0.1/15A507. it works well without patch. I think it was xcode issue

**Comment by noomorph** [comment] 2023-11-01 07:47
@PetroPavlenko, thanks for the new info. Indeed, I started my investigation straight from the latest Xcode version. Maybe 15.0.0 indeed had an issue. 🤷 

**Can anyone else confirm?**

**Comment by elliotmrodriguez** [comment] 2023-11-01 13:07
At the moment, the best I can share is I was already on 15.0.1 but I updated the detox library to 20.13.5. I now have to update all my configurations (was previously on v19), but just running it as a one-off with legacy configurations I did see deprecation warnings, which looks better than what was happening before... will add more after validating with correct configuration.

**Comment by kvramyasri7** [comment] 2023-11-02 17:13
[Code Of Conduct](https://opensource.guide/code-of-conduct/ ). Please follow community guidelines.

**Comment by kg-currenxie** [comment] 2023-11-14 03:09
> Hi @noomorph At the moment, the best I can share is I was already on 15.0.1 but I updated the detox library to 20.13.5. I now have to update all my configurations (was previously on v19), but just running it as a one-off with legacy configurations I did see deprecation warnings, which looks better than what was happening before... will add more after validating with correct configuration.
> 
> EDIT - I also have success after updating to latest detox package and applying correct new configurations. I was already on 15.0.1 before I updated. Whether it is an M series issue is still not clear to me. I have other colleagues using the older 19.13.x version of detox with 15.0.1 and it works, but they are on Ventura while I am on Sonoma, so I am curious if there is an OS component involved here too.

Similar here. A colleague is on Xcode 14 + Ventura (works), and I'm on Xcode 15 + Sonoma (doesn't work). Detox on 20.x

**Comment by ja-ka** [comment] 2023-11-24 12:03
Also worked for me after upgrading to RN 0.72.7 and detox 20.13.5

**Comment by Sulaimanma** [comment] 2023-12-01 00:24
react-native "0.71.14", encountered the same issue. Then upgraded detox from "^20.5.0" to "^20.13.5", the issue resolved. By the way, my xcode version is "15.0.1/15A507"

**Comment by phoet** [comment] 2024-01-12 12:22
i think this was due to https://forums.developer.apple.com/forums/thread/699615 and was fixed here already, so updating detox should do the trick.

**Comment by whalemare** [comment] 2024-03-19 18:53
detox: 20.11.1 - has issue, unable to run
detox: 20.19.3 - no issue, works correctly

**Comment by asafkorem** [comment] 2024-03-20 06:13
The issue reported by @TheChrisOneil has been already addressed, it was resolved in version [`20.11.4`](https://github.com/wix/Detox/releases/tag/20.11.4). We highly recommend upgrading to the latest version of Detox.

If any of the commenters continue to encounter errors after upgrading, please open a new issue. We are more than willing to assist further 🙏🏼

**Closed by asafkorem** 2024-03-20 06:13 UTC
Labels: type: bug 🐞, user: more info needed, platform: ios, status: accepted

**Comment by jeremyeaton89** [comment] 2024-03-20 18:08
i'm running into the issue still with detox 20.19.1 when using xcode 15.2.0 in circleci.

**Comment by Arron-Gill** [comment] 2024-04-24 16:26
> i'm running into the issue still with detox 20.19.1 when using xcode 15.2.0 RN 0.70.13 in circleci.

Adding this before the yarn detox call worked for me: 
`NODE_OPTIONS='--dns-result-order=ipv4first'`.

**Context:** Node 18 prefers IPv6 over IPv4 and I had just bumped from Node 16 to 18.
**Tested:** detox 20.19.3 using Xcode 15.2 with RN 0.73.7

**Comment by Sameer-Ijaz** [comment] 2024-07-16 11:56
You can probably solve this by doing this https://www.youtube.com/watch?v=9bDDWNoibIk
