### ISSUE TITLE
Could not cast value of type 'DetoxAppDelegateProxy' (0x1043b7118) to 'AppDelegate' (0x104142a68).

### ISSUE THREAD

**Issue by pvinis** [wix/detox#165] opened 2017-06-20 10:16 UTC
this error appears on the simulator system log, during the detox init.
then the init just times out.

**Comment by LeoNatan** [comment] 2017-06-22 12:02
I need more info. Please provide a demo project that replicates this. Thanks

**Comment by LeoNatan** [comment] 2017-07-05 10:17
@pvinis Hello. Still waiting for that demo project. Thanks

**Comment by LeoNatan** [comment] 2017-07-23 21:17
Hmm, this seems to be the issue discussed elsewhere about Swift.

**Comment by jlongster** [comment] 2017-07-24 18:34
@LeoNatan Yep, I am hitting this as well. Unfortunately this is a closed source app so I can't show it. This is the full stack trace:

```
Could not cast value of type 'DetoxAppDelegateProxy' (0x10560bed0) to 'Blink.AppDelegate' (0x104fef0e0).
Signal caught: Abort trap: 6
0   EarlGrey                            0x000000011d478339 grey_signalHandler + 249
1   libsystem_platform.dylib            0x000000010d70bb3a _sigtramp + 26
2   libsystem_kernel.dylib              0x000000010d6cf430 libsystem_kernel.dylib + 1072
3   libsystem_c.dylib                   0x000000010d47a88f abort + 127
4   libswiftCore.dylib                  0x000000010cb32d55 _ZN5swift10fatalErrorEjPKcz + 149
5   libswiftCore.dylib                  0x000000010cb10dbb _ZN5swift24swift_dynamicCastFailureEPKvPKcS1_S3_S3_ + 75
6   libswiftCore.dylib                  0x000000010cb10e20 swift_dynamicCastClass + 0
7   libswiftCore.dylib                  0x000000010cb10ec0 swift_dynamicCastClassUnconditional + 80
8   Blink                               0x000000010490684c _TFC5Blink11ChatManager10deactivatefT_T_ + 204
9   Blink                               0x00000001049077d0 _TFC5Blink11ChatManagerD + 32
10  Blink                               0x0000000104907822 _TToFC5Blink11ChatManagerD + 34
11  libobjc.A.dylib                     0x000000010642fb8e _ZN11objc_object17sidetable_releaseEb + 202
12  Blink                               0x0000000104bdb5a8 -[RCTModuleData .cxx_destruct]
```

We use Swift heavily, and it's interesting that I see a reference to the `deactivate` method of our `ChatManager` class. Can you explain what `DetoxAppDelegateProxy` is and I might be able to figure this out?

**Comment by jlongster** [comment] 2017-07-24 18:37
Oh, I be this is the line that's failing:

```swift
        let appDelegate  = UIApplication.shared.delegate as! AppDelegate
```

I'm guessing detox injects a different delegate class or something? I'm not too advanced with Swift. Any pointers on what I should debug next? I'll keep looking, and if I can't figure it out I'll try to make a demo project.

**Comment by jlongster** [comment] 2017-07-24 18:39
I am able to get it work if I comment out these lines! So the question is: how can we get access to the app delegate in Swift?

**Comment by LeoNatan** [comment] 2017-07-24 19:00
I think I have an idea why it happens and will be able to provide a fix soon.
The problem is the strict Swift checking; proxy objects need to be more careful.

**Comment by pvinis** [comment] 2017-07-25 09:20
my app is also a mix of swift and objc. @jlongster how did you get that stacktrace?

**Comment by LeoNatan** [comment] 2017-07-30 04:57
Alright guys, I pushed a fix for this issue. Apologies it took a while. Should be available in the next release of Detox.

**Closed** 2017-07-30 04:56 UTC
Labels: bug
