### ISSUE TITLE
Yarn install fails with XCode 10.2 on MacOS 10.14.3

### ISSUE THREAD

**Issue by levi-beers** [wix/Detox#1236] opened 2019-03-26 20:15 UTC
**Describe the bug**
Cannot install Detox (any version including 12.0.0) in any RN project using XCode 10.2 on MacOS. For note, I also tried lower versions of Detox down to version 9. Still fails the same way. 

**To Reproduce**

1. Run `yarn install` from any RN project containing Detox with XCode 10.2

**Error**
```
Error: Command failed: /Users/levibeers/standard_apps/react-native-starter/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Object.<anonymous> (/Users/levibeers/standard_apps/react-native-starter/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
```

**Environment (please complete the following information):**
 - Detox: 12.0.0
 - React Native: 0.59.1
 - Node: 10.13.0
 - Device: Macbook Pro
 - Xcode: 10.2
 - iOS: N/A
 - macOS: 10.14.3

**Device and Verbose Detox Logs**
> Can't get that far

**iOS Framework Build Logs**
> Can't get that far

**Comment by fbartho** [comment] 2019-03-26 22:30
I exhibited this issue today, but then I switched from Detox 10 to Detox 12.0.0 and the problem went away. Instead I'm exhibiting a "can't find simulator" issue.

**Comment by levi-beers** [comment] 2019-03-26 22:38
I had to downgrade to XCode 10.1 for the moment. Hoping a few days clears up the issue.

**Comment by ddzirt** [comment] 2019-03-27 07:29
> I exhibited this issue today, but then I switched from Detox 10 to Detox 12.0.0 and the problem went away. Instead I'm exhibiting a "can't find simulator" issue.

Please make sure you not only updated macOS and xCode, but command line tools(and simulators), so it works.

My spec is: 
```
macOS Mojave: 10.14.4
xCode: 10.2
Node: 11.12.0
Yarn: 1.15.2
React Native: 0.59.2
Detox: 12.0.0
```

**Comment by LeoNatan** [comment] 2019-03-27 08:39
please attach the detox build log.

**Comment by todorone** [comment] 2019-03-27 12:22
After upgrading to detox `12`, you need to remove `node_modules` folder and clear building cache. Otherwise bug did not go for me...

**Comment by rajivshah3** [comment] 2019-03-30 03:47
I'm running into this issue as well. In my case it's probably because of two conflicting versions of Detox (`detox@12.1.1, which I've specified in `dependencies`, and `detox@9.1.2`, which [jet](https://github.com/invertase/jet) depends on). The issue happens when I run `yarn`, but not when I run `detox build-framework-cache`:

<details>
<summary>detox clean-framework-cache && detox build-framework-cache</summary>
```
Rajivs-MBP:tests rajiv$ detox clean-framework-cache
detox[46233] INFO:  [clean-framework-cache.js] Removing framework binaries from /Users/rajiv/Library/Detox
Rajivs-MBP:tests rajiv$ detox build-framework-cache
+ xcodebuild -version
+++ dirname /Users/rajiv/safetynet/tests/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/rajiv/safetynet/tests/node_modules/detox/scripts
+ detoxRootPath=/Users/rajiv/safetynet/tests/node_modules/detox
++ node -p 'require('\''/Users/rajiv/safetynet/tests/node_modules/detox/package.json'\'').version'
+ detoxVersion=12.1.1
++ echo 12.1.1
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=dc7ba1323c33dce4317f362c4323444da0552271
+ detoxFrameworkDirPath=/Users/rajiv/Library/Detox/ios/dc7ba1323c33dce4317f362c4323444da0552271
+ detoxFrameworkPath=/Users/rajiv/Library/Detox/ios/dc7ba1323c33dce4317f362c4323444da0552271/Detox.framework
+ main
+ '[' -d /Users/rajiv/Library/Detox/ios/dc7ba1323c33dce4317f362c4323444da0552271 ']'
+ prepareAndBuildFramework
+ '[' -d /Users/rajiv/safetynet/tests/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ extractSources /Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ detoxSourcePath=/Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ tar -xjf /Users/rajiv/safetynet/tests/node_modules/detox/Detox-ios-src.tbz -C /Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ buildFramework /Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ detoxSourcePath=/Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/rajiv/safetynet/tests/node_modules/detox/ios_src...'
Building Detox.framework from /Users/rajiv/safetynet/tests/node_modules/detox/ios_src...
+ mkdir -p /Users/rajiv/Library/Detox/ios/dc7ba1323c33dce4317f362c4323444da0552271
+ /Users/rajiv/safetynet/tests/node_modules/detox/scripts/build_universal_framework.sh /Users/rajiv/safetynet/tests/node_modules/detox/ios_src/Detox.xcodeproj /Users/rajiv/Library/Detox/ios/dc7ba1323c33dce4317f362c4323444da0552271
+ rm -fr /Users/rajiv/safetynet/tests/node_modules/detox/ios_src
+ echo Done
Done
```
</details>

<details>
<summary>rm -rf node_modules && yarn</summary>
```
Rajivs-MBP:tests rajiv$ rm -rf node_modules && yarn
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > jet@0.3.0" has incorrect peer dependency "detox@^9.0.1".
warning " > react-native-google-safetynet@0.3.3" has incorrect peer dependency "react-native@^0.48.0".
[4/4] 🔨  Building fresh packages...
[-/4] ⠂ waiting...
[4/4] ⠂ detox
[-/4] ⠂ waiting...
warning Error running install script for optional dependency: "/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox
Output:
+ xcodebuild -version
+++ dirname /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/scripts
+ detoxRootPath=/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox
++ node -p 'require('\\''/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/package.json'\\'').version'
+ detoxVersion=9.1.2
++ echo 9.1.2
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=f3d84a6ca691e4716a7feb49ebd444abeb805f04
+ detoxFrameworkDirPath=/Users/rajiv/Library/Detox/ios/f3d84a6ca691e4716a7feb49ebd444abeb805f04
+ detoxFrameworkPath=/Users/rajiv/Library/Detox/ios/f3d84a6ca691e4716a7feb49ebd444abeb805f04/Detox.framework
+ main
+ '[' -d /Users/rajiv/Library/Detox/ios/f3d84a6ca691e4716a7feb49ebd444abeb805f04 ']'
+ prepareAndBuildFramework
+ '[' -d /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
+ extractSources /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
+ detoxSourcePath=/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
+ mkdir -p /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
Extracting Detox sources...
+ tar -xjf /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/Detox-ios-src.tbz -C /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
+ buildFramework /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
+ detoxSourcePath=/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src...'
+ mkdir -p /Users/rajiv/Library/Detox/ios/f3d84a6ca691e4716a7feb49ebd444abeb805f04
Building Detox.framework from /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src...
+ /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/scripts/build_universal_framework.sh /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/ios_src/Detox.xcodeproj /Users/rajiv/Library/Detox/ios/f3d84a6ca691e4716a7feb49ebd444abeb805f04
child_process.js:625
    throw err;
    ^

Error: Command failed: /Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at Object.<anonymous> (/Users/rajiv/safetynet/tests/node_modules/jet/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
✨  Done in 40.64s.
```
</details>

I can't reproduce this using the `demo-react-native` project in this repo. It might be worth checking if you have a dependency that uses `detox` though

**Comment by LeoNatan** [comment] 2019-03-30 10:42
Mixing Detox versions is not supported. Sounds like Jet is doing something very wrong. Not sure what you expect us to do. I suggest removing that dependency.

**Comment by ScreamZ** [comment] 2019-04-01 08:45
same issue here, any idea how to proceed well ?

**Comment by ikabelerma** [comment] 2019-04-01 09:04
I ran into this problem and had to downgrade to XCode 10.2 and it worked. I'm using detox 10.0.12.

From 10.1 to 10.2, they released a [breaking change](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2) for Swift 3:

> Swift 5 no longer supports the Swift 3 Package.swift tools-version. Packages still on the Swift 3 Package.swift tools-version should update to a newer tools-version. (41974124)

I only realized this when I was trying to debug this and tried to open Detox.xworkspace on XCode 10.1 and got an error message:
<img width="1512" alt="Screenshot 2019-04-01 at 4 07 42 PM" src="https://user-images.githubusercontent.com/8060373/55316031-1d9f7200-54a0-11e9-8650-651fc9de6d16.png">

**Comment by ScreamZ** [comment] 2019-04-01 10:43
**Update :**

It work using Xcode 10.2 if you install at least detox >= 12.

don't forget to `rm -rf node/modules/ ios/build/`

**Comment by rajivshah3** [comment] 2019-04-01 11:25
> Mixing Detox versions is not supported and cannot really work, if you think about it. Sounds like Jet is doing something very wrong. Not sure what you expect us to do. I suggest removing that dependency.

@LeoNatan I didn’t expect any help from the Detox team regarding that issue. I was simply suggesting it as a possible cause

**Comment by LeoNatan** [comment] 2019-04-01 11:31
I’m closing the issue now. We consider all Xcode 10.2 issues to be resolved.

**Closed by LeoNatan** 2019-04-01 11:31 UTC
Labels: platform: ios, type: triage/bug, user: more info needed
