### ISSUE TITLE
git submodules prevent from switching branches

### ISSUE THREAD

**Issue by talkol** [wix/detox#49] opened 2016-11-30 21:57 UTC
maybe a new approach?

**Comment by LeoNatan** [comment] 2016-12-20 07:54
This seems like "by design" of Git.

**Comment by talkol** [comment] 2016-12-20 17:10
is it possible to add a remark in the README of detox/detox with a short explanation of this issue and what to do it about it? (a command line that deletes what needs to be deleted)?

**Comment by rotemmiz** [comment] 2017-01-10 20:03
we are way past the v3 era, and v4 is in master. closing.

**Closed by rotemmiz** 2017-01-10 20:03 UTC
Labels: not_a_bug
