### ISSUE TITLE
Detox's longPress action is triggering onPressIn, onPressOut, and onLongPress at the same time

### ISSUE THREAD

**Issue by swindiggie** [wix/Detox#2950] opened 2021-08-20 13:04 UTC
### Description

When using Detox's [longPress](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#longpressduration) action, the `onPressIn`, `onPressOut`, and `onLongPress` props for `TouchableOpacity` are all getting triggered at the same time and not when I would expect them to be triggered.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Pass a callback handler for `onPressIn`, `onPressOut`, and `onLongPress` to to `TouchableOpacity`:
```
<TouchableOpacity
  testID="test button"
  onPress={logOnPress}
  onPressIn={logOnPressIn}
  onPressOut={logOnPressOut}
/>
```

2. Use Detox's `longPress` action:
```
element(by.id('test button')).longPress();
```

3. See that the callbacks for `onPressIn`, `onPressOut` and `onLongPress` are all getting triggered at roughly the same time, which was at the end of the long press action in my tests:
```
[11:16:07.461] LOG onPressIn called
[11:16:07.463] LOG onLongPress called
[11:16:07.464] LOG onPressOut called
```

#### Expected behavior
When using `longPress`, I would expect
1. `onPressIn` to get triggered immediately
2. `onLongPress` to get triggered at [delayLongPress](https://reactnative.dev/docs/touchablewithoutfeedback#delaylongpress) (default is 370 milliseconds)
3. `onPressOut` to get triggered at the end of the duration passed into Detox's `longPress` action (default is 1 second).

#### Environment (please complete the following information):
 - Detox: 18.20.1
 - React Native: 0.64.2
 - Node: 12.13.0
 - Device: iPad Pro (12.9-inch) (4th generation)
 - Xcode: 12.5.1
 - iOS: 14.5
 - macOS: 11.3.1 Big Sur

### Logs

Verbose logs provided down below.

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

Here are the logs from around the long press in my test. Let me know if you would like some more logs.
```
detox[23916] TRACE: [WS_SEND] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“getAttributes”,“predicate”:{“type”:“id”,“value”:“timestamp”}},“messageId”:13}
detox[23916] TRACE: [WSS_GET_FROM, #tester] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“getAttributes”,“predicate”:{“type”:“id”,“value”:“timestamp”}},“messageId”:13}
detox[23916] TRACE: [WSS_SEND_TO, #app] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“getAttributes”,“predicate”:{“type”:“id”,“value”:“timestamp”}},“messageId”:13}
detox[23916] TRACE: [WSS_GET_FROM, #app] {“params”:{“safeAreaInsets”:{“right”:0,“top”:0,“left”:0,“bottom”:0},“hittable”:true,“activationPoint”:{“x”:18.75,“y”:7.5},“frame”:{“y”:881,“x”:26,“width”:37.5,“height”:15},“elementFrame”:{“y”:0,“x”:10,“width”:37.5,“height”:15},“className”:“RCTTextView”,“normalizedActivationPoint”:{“x”:0.5,“y”:0.5},“visible”:true,“label”:“00:06”,“layer”:“<CALayer: 0x6000004cb9c0>“,”identifier”:“timestamp”,“elementSafeBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“text”:“00:06",“elementBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“enabled”:true},“messageId”:13,“type”:“invokeResult”}
detox[23916] TRACE: [WSS_SEND_TO, #tester] {“params”:{“safeAreaInsets”:{“right”:0,“top”:0,“left”:0,“bottom”:0},“hittable”:true,“activationPoint”:{“x”:18.75,“y”:7.5},“frame”:{“y”:881,“x”:26,“width”:37.5,“height”:15},“elementFrame”:{“y”:0,“x”:10,“width”:37.5,“height”:15},“className”:“RCTTextView”,“normalizedActivationPoint”:{“x”:0.5,“y”:0.5},“visible”:true,“label”:“00:06”,“layer”:“<CALayer: 0x6000004cb9c0>“,”identifier”:“timestamp”,“elementSafeBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“text”:“00:06",“elementBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“enabled”:true},“messageId”:13,“type”:“invokeResult”}
detox[23916] TRACE: [WS_MESSAGE] {“params”:{“safeAreaInsets”:{“right”:0,“top”:0,“left”:0,“bottom”:0},“hittable”:true,“activationPoint”:{“x”:18.75,“y”:7.5},“frame”:{“y”:881,“x”:26,“width”:37.5,“height”:15},“elementFrame”:{“y”:0,“x”:10,“width”:37.5,“height”:15},“className”:“RCTTextView”,“normalizedActivationPoint”:{“x”:0.5,“y”:0.5},“visible”:true,“label”:“00:06”,“layer”:“<CALayer: 0x6000004cb9c0>“,”identifier”:“timestamp”,“elementSafeBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“text”:“00:06",“elementBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“enabled”:true},“messageId”:13,“type”:“invokeResult”}
detox[23916] TRACE: [WS_SEND] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“longPress”,“params”:[5000],“predicate”:{“type”:“id”,“value”:“Slow Motion Forward”}},“messageId”:14}
detox[23916] TRACE: [WSS_GET_FROM, #tester] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“longPress”,“params”:[5000],“predicate”:{“type”:“id”,“value”:“Slow Motion Forward”}},“messageId”:14}
detox[23916] TRACE: [WSS_SEND_TO, #app] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“longPress”,“params”:[5000],“predicate”:{“type”:“id”,“value”:“Slow Motion Forward”}},“messageId”:14}
detox[23916] TRACE: [WSS_GET_FROM, #app] {“messageId”:14,“params”:{},“type”:“invokeResult”}
detox[23916] TRACE: [WSS_SEND_TO, #tester] {“messageId”:14,“params”:{},“type”:“invokeResult”}
detox[23916] TRACE: [WS_MESSAGE] {“messageId”:14,“params”:{},“type”:“invokeResult”}
detox[23916] TRACE: [WS_SEND] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“getAttributes”,“predicate”:{“type”:“id”,“value”:“timestamp”}},“messageId”:15}
detox[23916] TRACE: [WSS_GET_FROM, #tester] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“getAttributes”,“predicate”:{“type”:“id”,“value”:“timestamp”}},“messageId”:15}
detox[23916] TRACE: [WSS_SEND_TO, #app] {“type”:“invoke”,“params”:{“type”:“action”,“action”:“getAttributes”,“predicate”:{“type”:“id”,“value”:“timestamp”}},“messageId”:15}
detox[23916] TRACE: [WSS_GET_FROM, #app] {“params”:{“elementFrame”:{“y”:0,“x”:10,“width”:37.5,“height”:15},“safeAreaInsets”:{“right”:0,“top”:0,“left”:0,“bottom”:0},“elementBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“enabled”:true,“frame”:{“y”:881,“x”:26,“width”:37.5,“height”:15},“identifier”:“timestamp”,“text”:“00:06",“label”:“00:06",“hittable”:true,“elementSafeBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“visible”:true,“layer”:“<CALayer: 0x6000004cb9c0>“,”normalizedActivationPoint”:{“x”:0.5,“y”:0.5},“className”:“RCTTextView”,“activationPoint”:{“x”:18.75,“y”:7.5}},“messageId”:15,“type”:“invokeResult”}
detox[23916] TRACE: [WSS_SEND_TO, #tester] {“params”:{“elementFrame”:{“y”:0,“x”:10,“width”:37.5,“height”:15},“safeAreaInsets”:{“right”:0,“top”:0,“left”:0,“bottom”:0},“elementBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“enabled”:true,“frame”:{“y”:881,“x”:26,“width”:37.5,“height”:15},“identifier”:“timestamp”,“text”:“00:06",“label”:“00:06",“hittable”:true,“elementSafeBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“visible”:true,“layer”:“<CALayer: 0x6000004cb9c0>“,”normalizedActivationPoint”:{“x”:0.5,“y”:0.5},“className”:“RCTTextView”,“activationPoint”:{“x”:18.75,“y”:7.5}},“messageId”:15,“type”:“invokeResult”}
detox[23916] TRACE: [WS_MESSAGE] {“params”:{“elementFrame”:{“y”:0,“x”:10,“width”:37.5,“height”:15},“safeAreaInsets”:{“right”:0,“top”:0,“left”:0,“bottom”:0},“elementBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“enabled”:true,“frame”:{“y”:881,“x”:26,“width”:37.5,“height”:15},“identifier”:“timestamp”,“text”:“00:06",“label”:“00:06",“hittable”:true,“elementSafeBounds”:{“y”:0,“x”:0,“width”:37.5,“height”:15},“visible”:true,“layer”:“<CALayer: 0x6000004cb9c0>“,”normalizedActivationPoint”:{“x”:0.5,“y”:0.5},“className”:“RCTTextView”,“activationPoint”:{“x”:18.75,“y”:7.5}},“messageId”:15,“type”:“invokeResult”}
```

**Comment by asafkorem** [comment] 2021-11-28 10:35
@swindiggie it seems like these are the dates of the logs but not of the actual events, I can't reproduce the same issue as you have. 

I've created a simple test with this `TouchableOpacity` object and `Text` views:
```jsx
<TouchableOpacity
  onPress={() => {this.setState({onPressCallbackDate: Date.now().toString()})}}
  onPressIn={() => {this.setState({onPressInCallbackDate: Date.now().toString()})}}
  onLongPress={() => {this.setState({onLongPressCallbackDate: Date.now().toString()})}}
  onPressOut={() => {this.setState({onPressOutCallbackDate: Date.now().toString()})}}
>
...
</TouchableOpacity>
...
<Text style={{ ... }} testID='onPressCallbackDate'>{this.state.onPressCallbackDate}</Text>
...
<Text style={{ ... }} testID='onPressCallbackDate'>{this.state.onPressInCallbackDate}</Text>
...
<Text style={{ ... }} testID='onPressCallbackDate'>{this.state.onLongPressCallbackDate}</Text>
...
<Text style={{ ... }} testID='onPressCallbackDate'>{this.state.onPressOutCallbackDate}</Text>
```

The test invoked the action:
```js
await element(by.text('Press Me')).longPress();
```

Result:
![image](https://user-images.githubusercontent.com/55082339/143764251-483bc892-56c9-4d7c-8bdf-f03344c4b197.png)

You can see that the delta between the press-in to the long-press callbacks is `514 ms`, and between the press-out and the long-press is `501 ms`. All seems to be as expected.

Can you please provide me a code that reproduce the issue you describe using [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate), or any other simple app?

Also, can you please explain me a bit more about the flow you're trying to test?

**Comment by asafkorem** [comment] 2021-11-28 10:44
@swindiggie is it possible that you experience this weird behaviour not only when Detox is running, but on a human long-press also?

However, it looks to me like there's a flushing of bunch of logs, and the times are not the real callbacks invocations times.

**Comment by asafkorem** [comment] 2021-11-30 12:28
@swindiggie I'm closing this issue, please read my comments above and try to reproduce the bug as I described (or print the times from the callbacks, this should be different from the timestamp of the log print). 

Let me know if you still experience any issue that you think is related to Detox.

**Closed by asafkorem** 2021-11-30 12:28 UTC
Labels: user: more info needed, z_platform: ios
