### ISSUE TITLE
--cleanup flag fails subsequent tests after first successful suite due to emulator crash

### ISSUE THREAD

**Issue by mbardauskas** [wix/Detox#1975] opened 2020-03-25 14:23 UTC
**Describe the bug**
`detox test --cleanup` fails subsequent tests after first successful suite due to emulator crash, while each suite is green when running them separately.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Have 2 green test suites
2. run `detox test --cleanup --configuration android`

**Expected behavior**
Detox moves to subsequent test suites without crashing the emulator.

**Screenshots**

**Device and Verbose Detox Logs**
```
detox[87923] INFO:  [DetoxServer.js] server listening on localhost:52057...
detox[87923] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:52057
detox[87923] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=4a4c7ec0-1a92-f426-0ee1-a24c370d1eec
detox[87923] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=4a4c7ec0-1a92-f426-0ee1-a24c370d1eec
detox[87923] DEBUG: [exec.js/EXEC_CMD, #0] "/Users/martynasb/Library/Android/sdk/emulator/emulator" -list-avds --verbose
detox[87923] DEBUG: [EmulatorDriver.js/ACQUIRE_DEVICE] Looking up a device based on Pixel_API_28
detox[87923] DEBUG: [exec.js/EXEC_CMD, #1] "/Users/martynasb/Library/Android/sdk/platform-tools/adb"  devices
detox[87923] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
emulator-14630  device
detox[87923] ERROR: [EmulatorTelnet.js/TELNET_ERROR]
  err: Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
detox[87923] INFO:  at e2e-utils/index.ts:3:11
```

**Environment (please complete the following information):**
 - Detox: 16.0.1
 - React Native: 0.61.5
 - Node: 10.16.2
 - Device: Pixel_2_API_28 emulator
 - OS: Android
 - Test-runner: Jest+jest-circus

**Comment by uloco** [comment] 2020-04-22 08:33
I got the same problem, but it does not matter if I provide the `--cleanup` flag. The firs test suite runs successfully and the next ones are failing with the same error as above.

* Detox: 16.2.1
* React Native: 0.61.5
* Node: 12.16.2
* Device: Pixel_XL_API_29 emulator
* OS: Android
* Test-runner: Jest

**Comment by tkovs** [comment] 2020-05-06 04:08
I am on the same situation.

**Comment by noomorph** [comment] 2020-05-06 06:22
Thanks! I am going to verify this. @d4vidi, any chance you can look at this before me?
I think I can do that no sooner than tomorrow... :disappointed:

**Comment by d4vidi** [comment] 2020-05-12 14:06
@uloco could you please submit a seperate issue? Though log is similar, it sounds the problem is not quite the same.

**Comment by mrbrentkelly** [comment] 2020-10-15 10:04
I'm facing a similar problem when using the cleanup configuration in `.detoxrc.json`

```json
  "behavior": {
    "cleanup": {
      "shutdownDevice": true
    }
  }
```

More details here https://github.com/wix/Detox/issues/2320#issuecomment-709001979

**Comment by lcruz09** [comment] 2021-07-13 12:22
Any updates on this? I am currently facing the same issue:

```
Detox: 18.8.1
React Native: 0.63.4
Node: 14.13.1
Device: Pixel_XL_API_29 on Android Emulator
OS: MacOS 10.15.7
Test-runner: Jest
```

**Comment by noomorph** [comment] 2021-07-13 14:25
Thanks for the reminder, @lcruz09.

I had a free hour and got to the bottom of that in #2892. 
It is going to take a bit more to refine the fix and discuss it with the team, but I hope it is going to arrive within 7-10 days.

**Comment by lcruz09** [comment] 2021-09-02 13:42
@noomorph seems like it's working quite nicely now 🚀! Thanks! 
Guess this can be marked as closed now

**Closed** 2021-11-19 12:03 UTC
Labels: 📌 pinned, z_platform: android, type: triage/bug
