### ISSUE TITLE
Setting notifications permissions to yes on launching does not work anymore (xcode 9, iOS 11)

### ISSUE THREAD

**Issue by Gys** [wix/detox#305] opened 2017-10-03 11:42 UTC
#### Description

Suddenly setting the notifications permissions to yes on launching does not work anymore.
It worked before, but now I have a system popup asking the user to allow notifications. That popup should not happen.

I think this popup is back again since I upgraded to xcode 9.0. Which also means the simulator is upgraded to iOS 11.0

During the test startup Detox reports:
detox info 7: Trying to set permissions... 
detox info 7: Permissions are set
However, it seems they do not.

#### Steps to Reproduce

```
before(async () => {
  await detox.init(config, { launchApp: false });
  await device.launchApp({ permissions: { notifications: 'YES' } });
});
```

#### Node, Device, Xcode and macOS Versions

* Node: 8.4.0
* Device: simulator iPhone 7 iOS 11.0
* Xcode: 9.0
* macOS: 10.12.6
* applesimutils: HEAD-1c62171
* detox: 5.8.1

**Comment by felippepuhle** [comment] 2017-10-03 12:01
Same here... I'm trying to get this working since yesterday....

**Comment by Gys** [comment] 2017-10-03 17:29
The problem seems running iOS 11 in the simulator. Because I do not have the problem anymore if I switch back to iOS 10.3(.1)

I installed iOS 10.3.1 (yes, .1) in xcode 9 and then selected that version in the package.json like below. For some reason there only 10.3 is accepted. 

After this the system notifications popup does not appear anymore.

```
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/HighFive.app",
        "build": "xcodebuild -project ios/HighFive.xcodeproj -scheme HighFive -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7, iOS 10.3"
      }
    }
  }
```

**Comment by LeoNatan** [comment] 2017-10-06 15:38
This will be fixed soon in AppleSimUtils.

**Closed by LeoNatan** 2017-10-06 15:38 UTC

**Comment by ahmedlhanafy** [comment] 2017-10-16 01:02
@LeoNatan It's still not working even after installing Detox and AppleSimUtils latest versions 😞

**Comment by LeoNatan** [comment] 2017-10-16 09:01
@ahmedlhanafy I’ll look into it.

**Comment by LeoNatan** [comment] 2017-10-16 09:30
@ahmedlhanafy Unable to reproduce your problem. What does `applesimutils --version` return?

**Comment by ahmedlhanafy** [comment] 2017-10-17 23:21
@LeoNatan My applesimutils version is `0.5.11 `.
Can this problem arise because I don't ask for push notifications permission when the app starts? In my case, I ask for permissions once the user logs in

**Comment by LeoNatan** [comment] 2017-10-18 09:42
0.5.11 supports Xcode 9.
But I don’t understand—if you are not asking for permission, how do you know it’s not working? If you ask for permission and no system alert comes up, that means it is working, otherwise not working.

**Comment by ahmedlhanafy** [comment] 2017-10-18 16:24
Sorry for the confusion, what I meant is, I ask for the permission once the user logs in. So when simulating login with Detox, it gets stuck on the first screen (after login) that shows the permission popup. I don't ask for the permission right away when the app starts, I delay asking for it until the user logs in.

**Comment by ahmedlhanafy** [comment] 2017-10-20 21:52
cc @LeoNatan
