### ISSUE TITLE
Jest CLI options such as --onlyChanged don’t work

### ISSUE THREAD

**Issue by sonicdoe** [wix/Detox#2901] opened 2021-07-16 13:57 UTC
### Description

[Jest CLI options](https://jestjs.io/docs/cli) such as [`--onlyChanged`](https://jestjs.io/docs/cli#--onlychanged) and [`--watch`](https://jestjs.io/docs/cli#--watch) don’t work because Detox always passes the `e2e` directory.

✓ I have tested this issue on the latest Detox release and it still reproduces.

#### Reproduction

1. Clone [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate).
2. Follow [the instructions](https://github.com/wix-incubator/DetoxTemplate/tree/1903b3e50ad5f8c2d8c98723084788e371b23a74#ios-in-debug-mode) there.
3. `npm install detox@18.19.0 --save-dev`
4. `npm run test:ios-debug -- --onlyChanged`

#### Expected behavior

Jest understands the `--onlyChanged` option and only runs tests which have changed.

#### Suggested solution

Detox explicitly passes the `e2e` directory when invoking Jest, for example, `jest --config e2e/config.json e2e`. When specifying both `--onlyChanged` and `e2e`, Jest gives preference to `e2e` and runs all tests.

However, specifying `e2e` is not really necessary because Jest defaults to running all tests matching [`testMatch`](https://jestjs.io/docs/configuration#testmatch-arraystring) in the [`rootDir`](https://jestjs.io/docs/configuration#rootdir-string). For example, `jest --config e2e/config.json` also executes all tests.

Without `e2e`, options such as `--onlyChanged` work. For example, you can invoke Jest manually with:

```console
$ DETOX_CONFIGURATION="ios.sim.debug" npx jest --config e2e/config.json --onlyChanged
```

Then, Jest properly exits with “No tests found related to files changed since last commit.”

#### Environment

 - Detox: 18.19.0
 - React Native: 0.64.4
 - Node: 14.17.3

**Comment by noomorph** [comment] 2021-07-16 18:55
@d4vidi, shall we add one more `skipLegacySpecsInjection`? 😆

**Comment by noomorph** [comment] 2021-07-16 18:59
@sonicdoe, may I suggest adding `specs: ' '` to your Detox config? Make sure it has whitespace inside.

**Comment by sonicdoe** [comment] 2021-07-19 09:41
Thanks, that works 👍 By the way, this `specs` option doesn’t seem to be documented in the [configuration options](https://github.com/wix/Detox/blob/18.19.0/docs/APIRef.Configuration.md).

**Comment by sonicdoe** [comment] 2021-08-19 08:26
This issue is still present in Detox v18.20.2.

**Comment by d4vidi** [comment] 2021-08-29 14:00
@noomorph something to address this week, maybe?

**Comment by sonicdoe** [comment] 2021-09-30 07:11
This issue is still present in Detox v18.22.0.

**Comment by sonicdoe** [comment] 2021-11-03 12:06
I haven’t tested it again, but looking at the changelog, I assume this is still present in the latest version.

**Comment by noomorph** [comment] 2021-11-29 10:54
This will be a breaking change.
I added it to the plan to Detox 20: https://github.com/wix/Detox/discussions/2838
Also, related issue: https://github.com/wix/Detox/issues/3076

**Comment by sonicdoe** [comment] 2022-06-20 06:31
I haven’t tested it again, but I assume this issue is still relevant.

**Comment by sonicdoe** [comment] 2022-07-25 06:21
I haven’t tested it again, but I assume this issue is still relevant.

**Comment by sonicdoe** [comment] 2022-09-09 06:28
I haven’t tested it again, but I assume this issue is still relevant.

**Comment by d4vidi** [comment] 2022-09-13 12:33
@noomorph wouldn't it be better off if the issue is merged with Detox 20?
Also, is `platform: non-specific` better than not specifying the platform altogehter?

**Comment by noomorph** [comment] 2022-11-17 17:36
I think this issue is no longer relevant for Detox 20.

Please create a new one if something does not work.
We don't use `specs` anymore.

**Closed by noomorph** 2022-11-17 17:36 UTC
Labels: type: enhancement ⚡️, status: accepted

**Comment by sonicdoe** [comment] 2022-11-22 11:07
Thanks! I can confirm that `--onlyChanged` now works properly with Detox v20.

**Comment by noomorph** [comment] 2022-11-22 11:09
@sonicdoe let me know if you experience issues in `-R, --retries` mode. I think this is likely, so if it confirms, I'll fix it.

**Comment by sonicdoe** [comment] 2022-11-24 13:59
As far as I can tell, `--onlyChanged` works fine with `--retries`; it respawns `jest` with `--onlyChanged` and the failed test file. If there are no changed files, it immediately exits and doesn’t retry anything.
