### ISSUE TITLE
[Epic] React Native 68 compliance

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3344] opened 2022-04-25 09:14 UTC
- [x] iOS compliance: test project
- [x] #3490
- [x] #3470
- [ ] #3492
- [x] #3480 

> may come in handy: https://blog.logrocket.com/exploring-react-natives-new-architecture/ 

TODO: New architecture

**Comment by mikehardy** [comment] 2022-04-27 15:00
Just saw this myself today and headed over to see if anyone else had logged it.

Here's the stack on android

```

04-27 08:05:17.117 12749 12966 I DetoxDispatcher: Handling action '_init' (ID #0)...
04-27 08:05:17.117 12749 12966 I Detox   : Connecting to server...
04-27 08:05:17.117 12749 12966 I DetoxWSClient: At connectToServer
04-27 08:05:17.208 12749 12966 E AndroidRuntime: FATAL EXCEPTION: detox.primary
04-27 08:05:17.208 12749 12966 E AndroidRuntime: Process: com.rngooglemobileadsexample, PID: 12749
04-27 08:05:17.208 12749 12966 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method addReactInstanceEventListener(Lcom/facebook/react/ReactInstanceManager$ReactInstanceEventListener;)V in class Lcom/facebook/react/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/~~VAxFxoawAhh38x9oShR7aQ==/com.rngooglemobileadsexample--16s4kdFHYA9cPU0S6gWyQ==/base.apk)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-27 08:05:17.208 12749 12966 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-27 08:05:17.208 12749 12966 E DetoxCrashHandler: Crash detected!!! thread=detox.primary (660)
04-27 08:05:17.213 12749 12968 D DetoxWSClient: At onOpen
```

Here's your commit with the diff that broke Detox+RN68+ https://github.com/facebook/react-native/commit/ce74aa4ed335d4c36ce722d47937b582045e05c4

Commit log is pretty helpful:

```
Summary:
Add ```ReactInstanceEventListener``` for Venice and migrate Bridge-only callsites from
- FbReactInstanceHolder.getReactInstanceManager().addReactInstanceEventListener()
- FbReactInstanceHolder.getReactInstanceManager().removeReactInstanceEventListener()

To:
- FbReactInstanceHolder.addReactInstanceEventListener()
- FbReactInstanceHolder.removeReactInstanceEventListener()
```

Here's your call site https://github.com/wix/Detox/blob/679ac4c131104e8f34dd5b42eb9984b67d72e287/detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt#L38

I see other minor-version-specific workarounds like this, would something like this be suitable, to use one API or the other?

https://github.com/wix/Detox/blob/679ac4c131104e8f34dd5b42eb9984b67d72e287/detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeExtension.kt#L135-L145

I think you have other machinery involved in building vs different react-native versions as well though, to deal with symbol availability depending on what version is in use? Not sure how exactly to do that, but hopefully this helps as a start at minimum

**Comment by mikehardy** [comment] 2022-04-27 16:18
Hey guess what! It's just a typing change on their part for the listener type. Basically it appears to be a Java "binary compatibility break" but the code still works based on my testing, as long as you install Detox as a compile dependency so you recompile it to get the new type signature of the listener for the API you are calling.

@xiongemi you logged the other issue for react-native 0.68+ - if you re-integrate Detox, but as a compile dependency, does it work for you? I think it will. https://wix.github.io/Detox/docs/introduction/android#setting-detox-up-as-a-compiling-dependency

**Comment by thelazurite-cell** [comment] 2022-04-28 11:53
> 
> @xiongemi you logged the other issue for react-native 0.68+ - if you re-integrate Detox, but as a compile dependency, does it work for you? I think it will. https://wix.github.io/Detox/docs/introduction/android#setting-detox-up-as-a-compiling-dependency

Hey! was also having this issue and this resolved it for me. Thank you 👍🏻

**Comment by mikehardy** [comment] 2022-04-28 12:15
@d4vidi looks like we have confirmation from two people (myself and @thelazurite-cell) that Detox does not currently seem to need a forward port just to work on RN68, though it will need a recompile + rn68-specific binary distribution to handle the listener interface hierarchy / java binary compatibility break.

There *are* changes in RN68 that would be good to adopt in order to be ready for the "non-bridge" / "Fabric" future, but just to run? A recompile might be all that's needed.

**Comment by mikehardy** [comment] 2022-04-28 15:44
Just wait till you try to support fabric / new architecture 😂, multiple aars one per version probably in detox future

**Comment by d4vidi** [comment] 2022-05-01 11:46
Sounds like a proper challenge 😅

**Comment by MrRio** [comment] 2022-05-08 06:56
Is there a rough timeline on basic 0.68 support? (Not the optional fabric/non-bridge stuff)

**Comment by d4vidi** [comment] 2022-05-08 14:32
Roughly a matter of weeks. I'm afraid we are caught up by other things at the moment.

**Comment by mikehardy** [comment] 2022-05-08 22:34
@MrRio to confirm: you have integrated Detox in the source method and you still have a problem? Because as far as I was able to see, if you integrate it in the optional source style, there were no problems, it works/worked with 0.68

**Comment by karlhorky** [comment] 2022-05-14 22:32
> @xiongemi you logged the other issue for react-native 0.68+ - if you re-integrate Detox, but as a compile dependency, does it work for you? I think it will. [wix.github.io/Detox/docs/introduction/android#setting-detox-up-as-a-compiling-dependency](https://wix.github.io/Detox/docs/introduction/android#setting-detox-up-as-a-compiling-dependency)

Also works for me, thanks!

Was able to fix my PR https://github.com/upleveled/hotline-bling-codealong/pull/47 with these changes to the GitHub Actions workflow (running this using Expo):

https://github.com/upleveled/hotline-bling-codealong/compare/3e1a2940841062fdfd9d1bcee2bc754584078653...10ce954b72ab64e3de117a86fcdeeb51cf013ef6

**Comment by xiongemi** [comment] 2022-06-07 21:03
i got an error `Plugin with id 'kotlin-android' not found.`

**Comment by xiongemi** [comment] 2022-06-13 15:15
thanks. it works when I change it to compiling dependency.

**Comment by tedcu** [comment] 2022-06-17 11:52
Hey guys! Great work so far.

I've been upgrading to 0.68 (while knowing Detox doesn't really support it yet) and I managed to get the tests running by switching to compiling dependency. However I only get the first test to run and the rest fail with:
```
[1] 11:19:35.406 detox[16261] ERROR: ChildProcessError: `/opt/android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code 1
[1]     at ChildProcess.<anonymous> (/home/circleci/project/node_modules/child-process-promise/lib/index.js:132:23)
[1]     at ChildProcess.emit (node:events:520:28)
[1]     at maybeClose (node:internal/child_process:1092:16)
[1]     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

This is in CI with release build. I understand that 0.68 support isn't quite there, but it's very promising that I get the first one green so I might as well ask if this error points to something you guys would know about.

Thanks!

**Comment by mikehardy** [comment] 2022-06-17 12:04
This:

> `/opt/android/sdk/platform-tools/adb -s emulator-5554 shell pm install -r -g -t /data/local/tmp/detox/Application.apk`

Looks like the sort of command you could run locally in an environment that emulates CI as much as possible (or you could add a step in CI that runs it, or you could run `adb logcat` and capture the log like https://github.com/invertase/react-native-firebase/blob/ee740f80501fdd2ea5184515c4840340fca55e63/.github/workflows/tests_e2e_android.yml#L186 / https://github.com/invertase/react-native-firebase/blob/ee740f80501fdd2ea5184515c4840340fca55e63/.github/workflows/tests_e2e_android.yml#L200-L210 and review the error to determine root cause

Right now unfortunately your error report may be reduced to "hey I tried it, and a command failed", which is not enough information to make progress

**Comment by tedcu** [comment] 2022-06-17 12:23
Hey I tried it, a command failed, and I took a shot in the dark to ask a question if this was something that would trigger an immediate light bulb. Thanks for the reply, I'll continue debugging this with the help of logcat.

**Comment by shamilovtim** [comment] 2022-06-24 19:19
I see some Android workarounds were posted. Do we know the fix on iOS for this yet?

**Comment by mikehardy** [comment] 2022-06-24 19:28
@shamilovtim what is "this" ?

https://stackoverflow.com/help/how-to-ask

(I don't have problems with iOS, personally so "this" is working great! But my "this" may not be your "this")

**Comment by shamilovtim** [comment] 2022-06-24 19:59
50% of the time I am receiving the following error on iOS when running a Detox test for iOS sim:

```
15:18:10.143 detox[7891] WARN:  [DetoxConnection.js/ERROR, #50663] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  params: [Object],
  type: 'AppWillTerminateWithError',
  messageId: -10000
}
```

I assumed that everyone would be getting this but it sounds like that's not the case?

**Comment by henninghall** [comment] 2022-07-01 11:51
> i got an error `Plugin with id 'kotlin-android' not found.`

You still need the kotlin part from the setup
```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
```
I had to set the kotlin version to '1.6.0' to get it to work with RN 0.69

**Comment by shamilovtim** [comment] 2022-07-12 15:20
I have a general question about building Detox to compile. It seems when I do this I trigger a bunch of other dependencies' issues in their `mergeDebugAndroidTestJavaResource` and various Gradle jobs like that. Is there a way of allowing only Detox to be a compile dependency without having my other dependencies start to throw compatibility problems?

**Comment by shamilovtim** [comment] 2022-07-13 16:16
I resolved most of the issues but have found in general that Android emulator is too slow and JS thread bottlenecked to be able to use Detox on it 😐

**Comment by mikehardy** [comment] 2022-07-19 03:20
In case anyone else is bitten by "the soloader" issue (https://github.com/facebook/SoLoader/issues/94) - resulting in android crash on running androidTests - that one is fixed in soloader 0.10.4, which is *not* pulled in by default in react-native 0.69.x or (unless it is fixed) in 0.70.x. You can probably override it in your `android/app/build.gradle` to resolve to 0.10.4 (or 0.10.1 I guess) but unless you do you will probably crash. I have filed react-native PR here to fix it hopefully in react-native 0.70.x https://github.com/facebook/react-native/pull/34213 when it releases (it is in RC phase still)

**Comment by josephbaylon** [comment] 2022-07-19 22:46
I've gotten past the original issue by applying the detox setup as a compiling dependency. However, I'm now getting this new error while running the test. The app is trying to connect to a server and this happens,
```
15:44:26.777 detox[29500] WARN:  [APP_NONRESPONSIVE] Application nonresponsiveness detected!
On Android, this could imply an ANR alert, which evidently causes tests to fail.
Here's the native main-thread stacktrace from the device, to help you out (refer to device logs for the complete thread dump):
com.github.anrwatchdog.ANRError: Application Not Responding for at least 5000 ms.
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = WAITING)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1023)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
	at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:251)
	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:280)
	at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:65)
	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:170)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEventSequence(UiControllerImpl.java:13)
	at com.wix.detox.espresso.action.DetoxMultiTap.injectEvents(DetoxMultiTap.kt:83)
	at com.wix.detox.espresso.action.DetoxMultiTap.sendTap(DetoxMultiTap.kt:55)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:6)
	at com.wix.detox.espresso.action.RNClickAction.perform(RNClickAction.java:55)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:22)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by mikehardy** [comment] 2022-07-19 23:02
Reanimated issue, looks like, or combination react native / reanimated

**Comment by josephbaylon** [comment] 2022-07-19 23:56
@mikehardy Thanks for looking into. Do you have any suggestions for a workaround? Thanks in advance!

**Comment by siddhantsoni** [comment] 2022-07-20 06:03
When might the RN 0.68 compliance be available on the master branch for starters?
@d4vidi @mikehardy

**Comment by d4vidi** [comment] 2022-07-20 13:20
@shamilovtim may I suggest: https://support.genymotion.com/hc/en-us/articles/4414396695569-Scale-your-e2e-React-Native-UI-testing-with-Detox-on-Genymotion-SaaS-Cloud-Android-virtual-devices

We are working on announcing official support in Detox v20

**Closed** 2022-07-20 20:09 UTC
Labels: type: enhancement ⚡️, status: accepted, cat: maintenance

**Comment by anshulkapoor0018** [comment] 2022-07-26 16:33
After the upgrade to Detox 19.8.2

I am still getting the error, check out the logs when I try to run the tests. It boots up the emulator successfully and then gives the following error instantly

`detox test -c android.debug --loglevel=trace --debug-synchronization 500`

09:23:55.792 detox[21946] INFO:  [test.js] DETOX_CONFIGURATION="android.debug" DETOX_DEBUG_SYNCHRONIZATION=500 DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1658852635785 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
09:24:00.483 detox[21947] INFO:  Detox e2e Testing is assigned to emulator-5554 (Pixel_4_XL_API_31)
09:26:53.376 detox[22009] DEBUG: [WSS_CONNECTION, #49197] registered a new connection.
09:26:53.397 detox[22009] TRACE: [WSS_GET_FROM, #49197] {"messageId":-10000,"type":"AppWillTerminateWithError","params":{"errorDetails":"@Thread detox.primary(55):\njava.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication\n\tat com.wix.detox.reactnative.ReactNativeExtension.waitForRNBootstrap(ReactNativeExtension.kt:58)\n\tat com.wix.detox.DetoxMain.initReactNativeIfNeeded(DetoxMain.kt:102)\n\tat com.wix.detox.DetoxMain.doInit(DetoxMain.kt:34)\n\tat com.wix.detox.DetoxMain.access$doInit(DetoxMain.kt:15)\n\tat com.wix.detox.DetoxMain$initActionHandlers$$inlined$with$lambda$1.handle(DetoxMain.kt:52)\n\tat com.wix.detox.adapters.server.ActionsExecutor$executeAction$$inlined$let$lambda$1.run(DetoxActionsDispatcher.kt:64)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat com.wix.detox.adapters.server.ActionsExecutor$1.run(DetoxActionsDispatcher.kt:50)\n\tat java.lang.Thread.run(Thread.java:920)\n\nCheck device logs for full details!"}}
09:26:53.398 detox[22009] WARN:  [DetoxConnection.js/ERROR, #49197] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  messageId: -10000,
  type: 'AppWillTerminateWithError',
  params: [Object]
}
09:24:03.582 detox[21947] INFO:  [APP_STATUS] The app seems to be idle`


Emulator: Pixel_4_XL_API_31
RN Version: 0.68
Detox Version: 19.8.2

**Comment by asafkorem** [comment] 2022-07-26 19:28
Thanks for the report @anshulkapoor0018 
Can you please open a [GH issue](https://github.com/wix/Detox/issues/new?assignees=&labels=type%3A+bug+%F0%9F%90%9E%2Cplatform%3A+android%2Cstatus%3A+triage&template=BUG_REPORT_ANDROID.yml) with the full logs (including device logs)?
