### ISSUE TITLE
Biometric authentication cannot be cancelled

### ISSUE THREAD

**Issue by calcazar** [wix/Detox#1121] opened 2019-01-16 21:24 UTC
#### Description
My team is currently writting detox tests for touch ID. At the moment we have the happy path working by using a combination of detox, execSync, and AppleSimulatorUtils. The happy path works, we enroll before we launch, emulate a finger print read using --finger, and we are on our way

The problem is trying to hit "Cancel" on the touch ID prompt. We tried tap at certain coordinates and it only taps the background and not the actual cancel button. Looking at the output of detox, it doesn't acknowledge the touch ID prompt at all. We went in to the xcode hierarchy view and even that view doesn't show the touch ID dialogue.

#### Steps to Reproduce

start a test and enroll the device with a finger print

run detox and try to tap on Cancel by any means necessary.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.4
* React Native: 57.1
* Node: 6.4.1
* Device: iPhone 7
* Xcode: 10
* macOS: Mojave

#### Device and verbose Detox logs

Everything works.. no errors, just can't tap cancel on the touch ID dialogue

**Comment by LeoNatan** [comment] 2019-01-23 14:14
Duplicate of #958, which has a workaround. Please use search before opening new issues.

**Comment by LeoNatan** [comment] 2019-01-23 14:18
Ah, cancel. Hmm

Can you please open an issue on AppleSimUtils?

**Comment by LeoNatan** [comment] 2019-01-23 14:20
I am not sure this can be supported in AppleSimUtils but I will take a look when I have time. Please open an issue there.

**Comment by calcazar** [comment] 2019-01-23 17:09
Will do! Thank you!

**Comment by LeoNatan** [comment] 2019-04-15 17:29
This should be in AppleSimUtils.

**Closed by LeoNatan** 2019-04-15 17:29 UTC
Labels: type: accepted/enhancement
